-- =========================
-- Localization.lua - Localization tables (deDE/enUS)
-- =========================

_G["AuctionatorMiniSearch"] = _G["AuctionatorMiniSearch"] or {}
local AMS = _G["AuctionatorMiniSearch"]

local locale = GetLocale and GetLocale() or "enUS"
if locale ~= "deDE" then
  locale = "enUS"
end

local locales = {
  enUS = {
    APP_TITLE = "Auctionator Mini Search (Retail)",
    OPTIONS_TITLE = "Auctionator Mini Search - Options",
    STATUS_READY = "Ready",
    STATUS_JOBS_ABORTED = "Jobs aborted",
    STATUS_INDEX_BUILDING = "Building index…",
    STATUS_NO_DATA_INDEXED = "No indexed data",
    STATUS_NO_DATA = "No data",
    STATUS_NO_MATCHES = "No matches",
    STATUS_MATCHES_FOUND_FMT = "%d matches found",
    STATUS_MATCHES_TOTAL_FMT = " (%d total, increase row count for more)",
    SEARCH_LABEL_FMT = "Item name (min. %d chars)",
    BUTTON_SEARCH = "Search",
    BUTTON_CLEAR = "Clear",
    TOOLTIP_SEARCH = "Search",
    TOOLTIP_CLEAR = "Clear",
    TOOLTIP_OPTIONS = "Options",
    MINIMAP_TOOLTIP_TITLE = "Auctionator Mini Search",
    MINIMAP_TOOLTIP_HINT = "Left-click: Open/close window\nDrag: Move icon",
    DEBUG_TOOLTIP_ACTIVE = "Debug mode active",
    DEBUG_TOOLTIP_SCAN = "/ams scan available",
    DEBUG_TOOLTIP_ICON = "Icon: Wrench",
    RESET_CONFIRM_TEXT = "Reset AuctionatorMiniSearch data?\n(Index, missing list and UI settings will be deleted.)",
    RESET_BUTTON = "Reset",
    CANCEL_BUTTON = "Cancel",
    TAB_GENERAL = "General",
    TAB_SEARCH = "Search",
    TAB_DATA = "Data",
    SECTION_DISPLAY = "Display",
    SECTION_SEARCH_BEHAVIOR = "Search behavior",
    SECTION_INDEX_STORAGE = "Index & Storage",
    OPTION_LIVE_SEARCH_LABEL = "Live search while typing",
    OPTION_LIVE_SEARCH_INFO = "When enabled, results update while typing.",
    OPTION_PRICE_TOOLTIP_LABEL = "Show price in tooltip",
    OPTION_PRICE_TOOLTIP_INFO = "Adds AMS price/range to the item tooltip.",
    OPTION_MINIMAP_ICON_LABEL = "Show minimap icon",
    OPTION_MINIMAP_ICON_INFO = "Shows or hides the AMS button on the minimap.",
    OPTION_MIN_CHARS_LABEL = "Minimum characters",
    OPTION_MIN_CHARS_INFO = "Defines from how many characters a search starts.",
    OPTION_KEEP_FOCUS_LABEL = "Keep focus after Enter",
    OPTION_KEEP_FOCUS_INFO = "If enabled, cursor stays in search box after Enter.",
    OPTION_DEBUG_LABEL = "Enable debug mode",
    OPTION_DEBUG_INFO = "Allows /ams scan and shows the debug icon in the main window.",
    OPTION_STATUS_DETAIL_LABEL = "Detailed status messages",
    OPTION_STATUS_DETAIL_INFO = "When OFF, long progress messages are shortened.",
    OPTION_REFRESH_DAYS_LABEL = "Refresh after days",
    OPTION_REFRESH_DAYS_INFO = "From this age, prices are refreshed in the background.",
    OPTION_AUTODELETE_DAYS_LABEL = "Auto-delete after days",
    OPTION_AUTODELETE_DAYS_INFO = "0 = off. From this age, entries are removed from AMS index during background refresh.",
    OPTION_REBUILD_INDEX_LABEL = "Rebuild index",
    OPTION_REBUILD_INDEX_INFO = "Starts a full rebuild from current Auctionator database.",
    OPTION_RESET_DATA_LABEL = "Reset data",
    OPTION_RESET_DATA_INFO = "Deletes stored AMS data and creates a fresh index.",
    CACHE_HINT = "|cffccccccNote: Some items appear in search only after they were seen once in-game (WoW cache).|r",
    STATUS_NO_CHAT_EDITBOX = "No open chat input available for shift-link.",
    TOOLTIP_AMS_PRICE_FMT = "AMS Price: %s",
    FALLBACK_ITEM_FMT = "Item %d",
    PRICE_RANGE_PREFIX = "|cff66c0ffRange|r ",
    PRICE_RANGE_TO = " |cff66c0ffto|r ",
    AGE_DAYS_FMT = "%d days",
    STATUS_PRICES_REFRESHING_BG = "Refreshing prices in background...",
    STATUS_PRICES_UPDATED_FMT = "Prices updated: %d",
    STATUS_PRICES_UPDATED_REMOVED_FMT = "Prices updated: %d | removed stale: %d",
    STATUS_ZEROPRICE_CHECKING = "Checking zero-price items...",
    STATUS_ZEROPRICE_UPDATED_FMT = "Zero-price items updated: %d",
    STATUS_ZEROPRICE_CHECK_DONE_FMT = "Zero-price check: %d checked",
    STATUS_INDEX_RECONCILING = "Reconciling index...",
    STATUS_INDEX_RECONCILE_ADDED_FMT = "Index reconcile: %d newly added",
    STATUS_INDEX_COMPLETE = "Index complete",
    STATUS_INDEX_RECONCILE_PROGRESS_FMT = "Index reconcile: %d%% (%d new)",
    STATUS_NO_MISSING_ITEMS_OPEN = "No missing items open",
    STATUS_ADDING_MORE_PRICES_PROGRESS_FMT = "Adding more prices to database... [%d%%] Please wait!",
    STATUS_CHECKING_MISSING_PROGRESS_FMT = "Checking missing items... [%d%%]",
    STATUS_MISSING_UPDATED_FMT = "Missing items updated: %d new, %d open",
    STATUS_NO_MISSING_ITEMS = "No missing items",
    STATUS_CHECKING_MISSING = "Checking missing items...",
    STATUS_CHECKING_MISSING_COUNT_FMT = "Checking missing items (%d)...",
    ERROR_INVALID_PRICE_DB = "Auctionator price database invalid or empty!",
    STATUS_INDEX_DB_SCANNING_PROGRESS_FMT = "Scanning price index database [%d%%] Please wait!",
    LOG_INDEX_FULLY_LOADED_FMT = "[AMS] Index fully loaded: %d items",
    STATUS_RESET_REBUILDING = "SavedVariables reset. Rebuilding index...",
    STATUS_SCAN_COOLDOWN_FMT = "Scan cooldown active: %d min left",
    ERROR_NO_PRICE_DB_SCAN = "No price database available. Please open Auctionator and run a scan.",
    LOG_AUCTIONATOR_NOT_INSTALLED = "[AMS] Error: Addon 'Auctionator' is not installed or enabled!",
    LOG_AUCTIONATOR_NOT_LOADED = "[AMS] Auctionator not loaded!",
    LOG_API_DETECTED = "[AMS] Auctionator API v1 detected.",
    LOG_API_NOT_FOUND_FALLBACK = "[AMS] Notice: Auctionator API v1 not found, using DB fallback.",
    LOG_DB_NIL_API_ACTIVE = "[AMS] AUCTIONATOR_PRICE_DATABASE is nil, API mode stays active.",
    LOG_DB_NIL = "[AMS] AUCTIONATOR_PRICE_DATABASE is nil!",
    LOG_DB_DESERIALIZE_ERROR = "[AMS] Error while deserializing price database!",
    LOG_NO_PRICE_DATA_REALM_FMT = "[AMS] No price data for realm: %s. Please open Auctionator and run a scan.",
    LOG_NO_PRICE_DATA_REALM_FACTION_FMT = "[AMS] No price data for realm/faction: %s",
    LOG_DB_LOADED = "[AMS] Database loaded. Index will be built on open.",
    LOG_API_MODE_ACTIVE = "[AMS] API mode active. Index will be built on open.",
    LOG_ERR_UI_NOT_LOADED = "[AMS] Error: UI was not loaded.",
    LOG_ERR_SEARCHBOX_NOT_INIT = "[AMS] Error: searchBox not initialized! Check if UI.lua is loaded correctly and listed before Core in .toc.",
    LOG_ERR_AUCTIONATOR_ADDON_INACTIVE = "[AMS] ERROR: Auctionator addon is not enabled!",
    LOG_SCAN_DEBUG_ONLY = "[AMS] /ams scan is only available in debug mode.",
    LOG_SCAN_ALREADY_RUNNING = "[AMS] Scan already running.",
    LOG_MANUAL_SCAN_STARTED = "[AMS] Manual scan started (debug).",
    LOG_DEBUG_MODE_FMT = "[AMS] Debug mode: %s",
    STATE_ON = "ON",
    STATE_OFF = "OFF",
    LOG_DEBUG_INVALID_ITEMID_FMT = "[AMS Debug] Invalid itemID: %s",
    LOG_DEBUG_HEADER_ITEMID_FMT = "[AMS Debug] === ItemID %d ===",
    LOG_DEBUG_IN_SEARCHINDEX_FMT = "[AMS Debug] ✓ In searchIndex: %s | Price: %s | LastCheck: %s",
    LOG_DEBUG_NOT_IN_SEARCHINDEX = "[AMS Debug] ✗ NOT in searchIndex",
    LOG_DEBUG_IN_MISSING_FMT = "[AMS Debug] ⚠ In missingItems (Retry: %d)",
    LOG_DEBUG_NOT_IN_MISSING = "[AMS Debug] ✓ NOT in missingItems",
    LOG_DEBUG_API_PRICE_FMT = "[AMS Debug] ✓ API price: %s",
    LOG_DEBUG_API_PRICE_NIL = "[AMS Debug] ✗ API price: nil",
    LOG_DEBUG_IN_PRICEDB_FMT = "[AMS Debug] ✓ In priceDB key '%s' | Price: %s",
    LOG_DEBUG_NOT_IN_PRICEDB = "[AMS Debug] ✗ NOT found in priceDB",
    LOG_DEBUG_PRICEDB_INVALID = "[AMS Debug] ✗ priceDB is nil/invalid",
    LOG_DEBUG_NAME_BY_ID_FMT = "[AMS Debug] ✓ GetItemNameByID: %s",
    LOG_DEBUG_NAME_BY_ID_NIL = "[AMS Debug] ✗ GetItemNameByID: nil",
    LOG_DEBUG_ITEM_INFO_FMT = "[AMS Debug] ✓ GetItemInfo: %s",
    LOG_DEBUG_ITEM_INFO_NIL = "[AMS Debug] ✗ GetItemInfo: nil",
    LOG_DEBUG_END = "[AMS Debug] === End ===",
  },
  deDE = {
    APP_TITLE = "Auctionator Mini Suche (Retail)",
    OPTIONS_TITLE = "Auctionator Mini Suche - Optionen",
    STATUS_READY = "Bereit",
    STATUS_JOBS_ABORTED = "Jobs abgebrochen",
    STATUS_INDEX_BUILDING = "Index wird aufgebaut…",
    STATUS_NO_DATA_INDEXED = "Keine indizierten Daten",
    STATUS_NO_DATA = "Keine Daten",
    STATUS_NO_MATCHES = "Keine Treffer",
    STATUS_MATCHES_FOUND_FMT = "%d Treffer gefunden",
    STATUS_MATCHES_TOTAL_FMT = " (%d insgesamt, erhöhe Zeilenanzahl für mehr)",
    SEARCH_LABEL_FMT = "Itemname (mind. %d Zeichen)",
    BUTTON_SEARCH = "Suchen",
    BUTTON_CLEAR = "Clear",
    TOOLTIP_SEARCH = "Suchen",
    TOOLTIP_CLEAR = "Clear",
    TOOLTIP_OPTIONS = "Optionen",
    MINIMAP_TOOLTIP_TITLE = "Auctionator Mini Suche",
    MINIMAP_TOOLTIP_HINT = "Linksklick: Fenster öffnen/schließen\nZiehen: Icon verschieben",
    DEBUG_TOOLTIP_ACTIVE = "Debug-Modus aktiv",
    DEBUG_TOOLTIP_SCAN = "/ams scan verfügbar",
    DEBUG_TOOLTIP_ICON = "Icon: Wrench",
    RESET_CONFIRM_TEXT = "AuctionatorMiniSearch-Daten zurücksetzen?\n(Index, Missing-Liste und UI-Einstellungen werden gelöscht.)",
    RESET_BUTTON = "Reset",
    CANCEL_BUTTON = "Abbrechen",
    TAB_GENERAL = "Allgemein",
    TAB_SEARCH = "Suche",
    TAB_DATA = "Daten",
    SECTION_DISPLAY = "Anzeige",
    SECTION_SEARCH_BEHAVIOR = "Suchverhalten",
    SECTION_INDEX_STORAGE = "Index & Speicherung",
    OPTION_LIVE_SEARCH_LABEL = "Live-Suche beim Tippen",
    OPTION_LIVE_SEARCH_INFO = "Wenn aktiv, werden Treffer direkt beim Schreiben aktualisiert.",
    OPTION_PRICE_TOOLTIP_LABEL = "Preis im Tooltip anzeigen",
    OPTION_PRICE_TOOLTIP_INFO = "Zeigt den AMS-Preis bzw. Preisbereich zusätzlich im Item-Tooltip an.",
    OPTION_MINIMAP_ICON_LABEL = "Minimap-Icon anzeigen",
    OPTION_MINIMAP_ICON_INFO = "Zeigt oder versteckt den AMS-Button an der Minimap.",
    OPTION_MIN_CHARS_LABEL = "Mindestzeichen",
    OPTION_MIN_CHARS_INFO = "Legt fest, ab wie vielen Zeichen eine Suche gestartet wird.",
    OPTION_KEEP_FOCUS_LABEL = "Fokus nach Enter behalten",
    OPTION_KEEP_FOCUS_INFO = "Wenn aktiv, bleibt der Cursor nach Enter im Suchfeld.",
    OPTION_DEBUG_LABEL = "Debug-Modus aktivieren",
    OPTION_DEBUG_INFO = "Erlaubt /ams scan und zeigt das Debug-Werkzeug-Icon im Hauptfenster an.",
    OPTION_STATUS_DETAIL_LABEL = "Detaillierte Statusmeldungen",
    OPTION_STATUS_DETAIL_INFO = "Bei AUS werden längere Fortschrittstexte auf kurze Meldungen reduziert.",
    OPTION_REFRESH_DAYS_LABEL = "Refresh ab Tagen",
    OPTION_REFRESH_DAYS_INFO = "Ab diesem Alter werden Preise im Hintergrund bevorzugt aktualisiert.",
    OPTION_AUTODELETE_DAYS_LABEL = "Auto-Löschen ab Tagen",
    OPTION_AUTODELETE_DAYS_INFO = "0 = aus. Ab diesem Alter werden Einträge beim Hintergrund-Refresh aus dem AMS-Index entfernt.",
    OPTION_REBUILD_INDEX_LABEL = "Index neu aufbauen",
    OPTION_REBUILD_INDEX_INFO = "Startet einen vollständigen Neuaufbau aus der aktuellen Auctionator-Datenbank.",
    OPTION_RESET_DATA_LABEL = "Daten zurücksetzen",
    OPTION_RESET_DATA_INFO = "Löscht gespeicherte AMS-Daten und erstellt einen frischen Index.",
    CACHE_HINT = "|cffccccccHinweis: Einige Items erscheinen erst in der Suche, nachdem sie im Spiel einmal gesehen wurden (WoW-Cache).|r",
    STATUS_NO_CHAT_EDITBOX = "Kein geöffneter Chat-Eingabebereich für Shift-Link.",
    TOOLTIP_AMS_PRICE_FMT = "AMS Preis: %s",
    FALLBACK_ITEM_FMT = "Item %d",
    PRICE_RANGE_PREFIX = "|cff66c0ffSpanne|r ",
    PRICE_RANGE_TO = " |cff66c0ffbis|r ",
    AGE_DAYS_FMT = "%d Tage",
    STATUS_PRICES_REFRESHING_BG = "Preise werden im Hintergrund aktualisiert...",
    STATUS_PRICES_UPDATED_FMT = "Preise aktualisiert: %d",
    STATUS_PRICES_UPDATED_REMOVED_FMT = "Preise aktualisiert: %d | veraltet entfernt: %d",
    STATUS_ZEROPRICE_CHECKING = "Zero-Preis Items werden geprüft...",
    STATUS_ZEROPRICE_UPDATED_FMT = "Zero-Preis Items aktualisiert: %d",
    STATUS_ZEROPRICE_CHECK_DONE_FMT = "Zero-Preis Check: %d geprüft",
    STATUS_INDEX_RECONCILING = "Index-Abgleich läuft...",
    STATUS_INDEX_RECONCILE_ADDED_FMT = "Index-Abgleich: %d neu hinzugefügt",
    STATUS_INDEX_COMPLETE = "Index vollständig",
    STATUS_INDEX_RECONCILE_PROGRESS_FMT = "Index-Abgleich: %d%% (%d neu)",
    STATUS_NO_MISSING_ITEMS_OPEN = "Keine fehlenden Items offen",
    STATUS_ADDING_MORE_PRICES_PROGRESS_FMT = "Weitere Preise werden in Datenbank hinzugefügt... [%d%%] Bitte warten!",
    STATUS_CHECKING_MISSING_PROGRESS_FMT = "Fehlende Items werden geprüft... [%d%%]",
    STATUS_MISSING_UPDATED_FMT = "Fehlende Items aktualisiert: %d neu, %d offen",
    STATUS_NO_MISSING_ITEMS = "Keine fehlenden Items",
    STATUS_CHECKING_MISSING = "Fehlende Items werden geprüft...",
    STATUS_CHECKING_MISSING_COUNT_FMT = "Fehlende Items werden geprüft (%d)...",
    ERROR_INVALID_PRICE_DB = "Auctionator-Preisdatenbank ungültig oder leer!",
    STATUS_INDEX_DB_SCANNING_PROGRESS_FMT = "Preis-Index-Datenbank wird durchsucht [%d%%] Bitte warten!",
    LOG_INDEX_FULLY_LOADED_FMT = "[AMS] Index vollständig geladen: %d Items",
    STATUS_RESET_REBUILDING = "SV zurückgesetzt. Index wird neu aufgebaut...",
    STATUS_SCAN_COOLDOWN_FMT = "Scan-Cooldown aktiv: noch %d Min",
    ERROR_NO_PRICE_DB_SCAN = "Keine Preisdatenbank vorhanden. Bitte Auctionator öffnen und einen Scan durchführen.",
    LOG_AUCTIONATOR_NOT_INSTALLED = "[AMS] Fehler: Das Addon 'Auctionator' ist nicht installiert oder aktiviert!",
    LOG_AUCTIONATOR_NOT_LOADED = "[AMS] Auctionator nicht geladen!",
    LOG_API_DETECTED = "[AMS] Auctionator API v1 erkannt.",
    LOG_API_NOT_FOUND_FALLBACK = "[AMS] Hinweis: Auctionator API v1 nicht gefunden, nutze DB-Fallback.",
    LOG_DB_NIL_API_ACTIVE = "[AMS] AUCTIONATOR_PRICE_DATABASE ist nil, API-Modus bleibt aktiv.",
    LOG_DB_NIL = "[AMS] AUCTIONATOR_PRICE_DATABASE ist nil!",
    LOG_DB_DESERIALIZE_ERROR = "[AMS] Fehler beim Deserialisieren der Preisdatenbank!",
    LOG_NO_PRICE_DATA_REALM_FMT = "[AMS] Keine Preisdaten für Realm: %s. Bitte Auctionator öffnen und einen Scan durchführen.",
    LOG_NO_PRICE_DATA_REALM_FACTION_FMT = "[AMS] Keine Preisdaten für Realm/Faction: %s",
    LOG_DB_LOADED = "[AMS] Datenbank geladen. Index wird beim Öffnen erstellt.",
    LOG_API_MODE_ACTIVE = "[AMS] API-Modus aktiv. Index wird beim Öffnen erstellt.",
    LOG_ERR_UI_NOT_LOADED = "[AMS] Fehler: UI wurde nicht geladen.",
    LOG_ERR_SEARCHBOX_NOT_INIT = "[AMS] Fehler: searchBox ist nicht initialisiert! Prüfe, ob UI.lua korrekt geladen wird und in der .toc ganz oben steht.",
    LOG_ERR_AUCTIONATOR_ADDON_INACTIVE = "[AMS] FEHLER: Auctionator-Addon ist nicht aktiviert!",
    LOG_SCAN_DEBUG_ONLY = "[AMS] /ams scan ist nur im Debug-Modus verfügbar.",
    LOG_SCAN_ALREADY_RUNNING = "[AMS] Scan läuft bereits.",
    LOG_MANUAL_SCAN_STARTED = "[AMS] Manueller Scan gestartet (Debug).",
    LOG_DEBUG_MODE_FMT = "[AMS] Debug-Modus: %s",
    STATE_ON = "AN",
    STATE_OFF = "AUS",
    LOG_DEBUG_INVALID_ITEMID_FMT = "[AMS Debug] Ungültige ItemID: %s",
    LOG_DEBUG_HEADER_ITEMID_FMT = "[AMS Debug] === ItemID %d ===",
    LOG_DEBUG_IN_SEARCHINDEX_FMT = "[AMS Debug] ✓ Im searchIndex: %s | Preis: %s | LastCheck: %s",
    LOG_DEBUG_NOT_IN_SEARCHINDEX = "[AMS Debug] ✗ NICHT im searchIndex",
    LOG_DEBUG_IN_MISSING_FMT = "[AMS Debug] ⚠ In missingItems (Retry: %d)",
    LOG_DEBUG_NOT_IN_MISSING = "[AMS Debug] ✓ NICHT in missingItems",
    LOG_DEBUG_API_PRICE_FMT = "[AMS Debug] ✓ API Preis: %s",
    LOG_DEBUG_API_PRICE_NIL = "[AMS Debug] ✗ API Preis: nil",
    LOG_DEBUG_IN_PRICEDB_FMT = "[AMS Debug] ✓ In priceDB Key '%s' | Preis: %s",
    LOG_DEBUG_NOT_IN_PRICEDB = "[AMS Debug] ✗ NICHT in priceDB gefunden",
    LOG_DEBUG_PRICEDB_INVALID = "[AMS Debug] ✗ priceDB ist nil/ungültig",
    LOG_DEBUG_NAME_BY_ID_FMT = "[AMS Debug] ✓ GetItemNameByID: %s",
    LOG_DEBUG_NAME_BY_ID_NIL = "[AMS Debug] ✗ GetItemNameByID: nil",
    LOG_DEBUG_ITEM_INFO_FMT = "[AMS Debug] ✓ GetItemInfo: %s",
    LOG_DEBUG_ITEM_INFO_NIL = "[AMS Debug] ✗ GetItemInfo: nil",
    LOG_DEBUG_END = "[AMS Debug] === Ende ===",
  },
}

-- Returns the default locale used by AMS content selection.
function AMS.GetDefaultLocale()
  local wowLocale = GetLocale and GetLocale() or "enUS"
  if wowLocale == "deDE" then
    return "deDE"
  end
  return "enUS"
end

-- Returns the currently active AMS locale.
function AMS.GetCurrentLocale()
  return AMS.GetDefaultLocale()
end

AMS.locale = locale

-- Select the active locale table and a fallback; then release the full locales
-- table so the unused locale's strings can be garbage-collected.
local _activeLocaleTable = locales[locale] or locales.enUS
local _fallbackLocaleTable = (locale ~= "enUS") and locales.enUS or nil
locales = nil  -- Allow GC of the inactive locale table

-- Resolves a localized key and applies optional string formatting args.
function AMS.L(key, ...)
  local text = _activeLocaleTable[key]
  if text == nil and _fallbackLocaleTable then
    text = _fallbackLocaleTable[key]
  end
  if text == nil then
    text = key
  end
  if select("#", ...) > 0 then
    local ok, formatted = pcall(string.format, text, ...)
    if ok then
      return formatted
    end
  end
  return text
end
