-- =========================
-- Localization.lua - Localization tables (deDE/enUS)
-- =========================

_G["AuctionatorMiniSearch"] = _G["AuctionatorMiniSearch"] or {}
local AMS = _G["AuctionatorMiniSearch"]

local locale = GetLocale and GetLocale() or "enUS"
if locale ~= "deDE" then
  locale = "enUS"
end

local locales = {
  enUS = {
    APP_TITLE = "Auctionator Mini Search (Retail)",
    OPTIONS_TITLE = "Auctionator Mini Search - Options",
    STATUS_READY = "Ready",
    STATUS_JOBS_ABORTED = "Jobs aborted",
    STATUS_INDEX_BUILDING = "Building index…",
    STATUS_NO_DATA_INDEXED = "No indexed data",
    STATUS_NO_DATA = "No data",
    STATUS_NO_MATCHES = "No matches",
    STATUS_MATCHES_FOUND_FMT = "%d matches found",
    STATUS_MATCHES_TOTAL_FMT = " (%d total, increase row count for more)",
    SEARCH_LABEL_FMT = "Item name (min. %d chars)",
    BUTTON_SEARCH = "Search",
    BUTTON_CLEAR = "Clear",
    TOOLTIP_SEARCH = "Search",
    TOOLTIP_CLEAR = "Clear",
    TOOLTIP_OPTIONS = "Options",
    MINIMAP_TOOLTIP_TITLE = "Auctionator Mini Search",
    MINIMAP_TOOLTIP_HINT = "Left-click: Open/close window\nDrag: Move icon",
    DEBUG_TOOLTIP_ACTIVE = "Debug mode active",
    DEBUG_TOOLTIP_SCAN = "/ams scan available",
    DEBUG_TOOLTIP_ICON = "Icon: Wrench",
    RESET_CONFIRM_TEXT = "Reset AuctionatorMiniSearch data?\n(Index, missing list and UI settings will be deleted.)",
    RESET_BUTTON = "Reset",
    CANCEL_BUTTON = "Cancel",
    TAB_GENERAL = "General",
    TAB_SEARCH = "Search",
    TAB_DATA = "Data",
    SECTION_DISPLAY = "Display",
    SECTION_SEARCH_BEHAVIOR = "Search behavior",
    SECTION_INDEX_STORAGE = "Index & Storage",
    OPTION_LIVE_SEARCH_LABEL = "Live search while typing",
    OPTION_LIVE_SEARCH_INFO = "When enabled, results update while typing.",
    OPTION_MINIMAP_ICON_LABEL = "Show minimap icon",
    OPTION_MINIMAP_ICON_INFO = "Shows or hides the AMS button on the minimap.",
    OPTION_MIN_CHARS_LABEL = "Minimum characters",
    OPTION_MIN_CHARS_INFO = "Defines from how many characters a search starts.",
    OPTION_KEEP_FOCUS_LABEL = "Keep focus after Enter",
    OPTION_KEEP_FOCUS_INFO = "If enabled, cursor stays in search box after Enter.",
    OPTION_DEBUG_LABEL = "Enable debug mode",
    OPTION_DEBUG_INFO = "Allows /ams scan and shows the debug icon in the main window.",
    OPTION_STATUS_DETAIL_LABEL = "Detailed status messages",
    OPTION_STATUS_DETAIL_INFO = "When OFF, long progress messages are shortened.",
    OPTION_REFRESH_DAYS_LABEL = "Refresh after days",
    OPTION_REFRESH_DAYS_INFO = "From this age, prices are refreshed in the background.",
    OPTION_AUTODELETE_DAYS_LABEL = "Auto-delete after days",
    OPTION_AUTODELETE_DAYS_INFO = "0 = off. From this age, entries are removed from AMS index during background refresh.",
    OPTION_REBUILD_INDEX_LABEL = "Rebuild index",
    OPTION_REBUILD_INDEX_INFO = "Starts a full rebuild from current Auctionator database.",
    OPTION_RESET_DATA_LABEL = "Reset data",
    OPTION_RESET_DATA_INFO = "Deletes stored AMS data and creates a fresh index.",
    CACHE_HINT = "|cffccccccNote: Some items appear in search only after they were seen once in-game (WoW cache).|r",
    STATUS_NO_CHAT_EDITBOX = "No open chat input available for shift-link.",
    FALLBACK_ITEM_FMT = "Item %d",
    PRICE_RANGE_PREFIX = "|cff66c0ffRange|r ",
    PRICE_RANGE_TO = " |cff66c0ffto|r ",
    AGE_DAYS_FMT = "%d days",
    STATUS_PRICES_REFRESHING_BG = "Refreshing prices in background...",
    STATUS_PRICES_UPDATED_FMT = "Prices updated: %d",
    STATUS_PRICES_UPDATED_REMOVED_FMT = "Prices updated: %d | removed stale: %d",
    STATUS_ZEROPRICE_CHECKING = "Checking zero-price items...",
    STATUS_ZEROPRICE_UPDATED_FMT = "Zero-price items updated: %d",
    STATUS_ZEROPRICE_CHECK_DONE_FMT = "Zero-price check: %d checked",
    STATUS_INDEX_RECONCILING = "Reconciling index...",
    STATUS_INDEX_RECONCILE_ADDED_FMT = "Index reconcile: %d newly added",
    STATUS_INDEX_COMPLETE = "Index complete",
    STATUS_INDEX_RECONCILE_PROGRESS_FMT = "Index reconcile: %d%% (%d new)",
    STATUS_NO_MISSING_ITEMS_OPEN = "No missing items open",
    STATUS_ADDING_MORE_PRICES_PROGRESS_FMT = "Adding more prices to database... [%d%%] Please wait!",
    STATUS_CHECKING_MISSING_PROGRESS_FMT = "Checking missing items... [%d%%]",
    STATUS_MISSING_UPDATED_FMT = "Missing items updated: %d new, %d open",
    STATUS_NO_MISSING_ITEMS = "No missing items",
    STATUS_CHECKING_MISSING = "Checking missing items...",
    STATUS_CHECKING_MISSING_COUNT_FMT = "Checking missing items (%d)...",
    ERROR_INVALID_PRICE_DB = "Auctionator price database invalid or empty!",
    STATUS_INDEX_DB_SCANNING_PROGRESS_FMT = "Scanning price index database [%d%%] Please wait!",
    LOG_INDEX_FULLY_LOADED_FMT = "[AMS] Index fully loaded: %d items",
    STATUS_RESET_REBUILDING = "SavedVariables reset. Rebuilding index...",
    STATUS_SCAN_COOLDOWN_FMT = "Scan cooldown active: %d min left",
    ERROR_NO_PRICE_DB_SCAN = "No price database available. Please open Auctionator and run a scan.",
    LOG_AUCTIONATOR_NOT_INSTALLED = "[AMS] Error: Addon 'Auctionator' is not installed or enabled!",
    LOG_AUCTIONATOR_NOT_LOADED = "[AMS] Auctionator not loaded!",
    LOG_API_DETECTED = "[AMS] Auctionator API v1 detected.",
    LOG_API_NOT_FOUND_FALLBACK = "[AMS] Notice: Auctionator API v1 not found, using DB fallback.",
    LOG_DB_NIL_API_ACTIVE = "[AMS] AUCTIONATOR_PRICE_DATABASE is nil, API mode stays active.",
    LOG_DB_NIL = "[AMS] AUCTIONATOR_PRICE_DATABASE is nil!",
    LOG_DB_DESERIALIZE_ERROR = "[AMS] Error while deserializing price database!",
    LOG_NO_PRICE_DATA_REALM_FMT = "[AMS] No price data for realm: %s. Please open Auctionator and run a scan.",
    LOG_NO_PRICE_DATA_REALM_FACTION_FMT = "[AMS] No price data for realm/faction: %s",
    LOG_DB_LOADED = "[AMS] Database loaded. Index will be built on open.",
    LOG_API_MODE_ACTIVE = "[AMS] API mode active. Index will be built on open.",
    LOG_ERR_UI_NOT_LOADED = "[AMS] Error: UI was not loaded.",
    LOG_ERR_SEARCHBOX_NOT_INIT = "[AMS] Error: searchBox not initialized! Check if UI.lua is loaded correctly and listed before Core in .toc.",
    LOG_ERR_AUCTIONATOR_ADDON_INACTIVE = "[AMS] ERROR: Auctionator addon is not enabled!",
    LOG_SCAN_DEBUG_ONLY = "[AMS] /ams scan is only available in debug mode.",
    LOG_SCAN_ALREADY_RUNNING = "[AMS] Scan already running.",
    LOG_MANUAL_SCAN_STARTED = "[AMS] Manual scan started (debug).",
    LOG_DEBUG_MODE_FMT = "[AMS] Debug mode: %s",
    STATE_ON = "ON",
    STATE_OFF = "OFF",
    LOG_DEBUG_INVALID_ITEMID_FMT = "[AMS Debug] Invalid itemID: %s",
    LOG_DEBUG_HEADER_ITEMID_FMT = "[AMS Debug] === ItemID %d ===",
    LOG_DEBUG_IN_SEARCHINDEX_FMT = "[AMS Debug] ✓ In searchIndex: %s | Price: %s | LastCheck: %s",
    LOG_DEBUG_NOT_IN_SEARCHINDEX = "[AMS Debug] ✗ NOT in searchIndex",
    LOG_DEBUG_IN_MISSING_FMT = "[AMS Debug] ⚠ In missingItems (Retry: %d)",
    LOG_DEBUG_NOT_IN_MISSING = "[AMS Debug] ✓ NOT in missingItems",
    LOG_DEBUG_API_PRICE_FMT = "[AMS Debug] ✓ API price: %s",
    LOG_DEBUG_API_PRICE_NIL = "[AMS Debug] ✗ API price: nil",
    LOG_DEBUG_IN_PRICEDB_FMT = "[AMS Debug] ✓ In priceDB key '%s' | Price: %s",
    LOG_DEBUG_NOT_IN_PRICEDB = "[AMS Debug] ✗ NOT found in priceDB",
    LOG_DEBUG_PRICEDB_INVALID = "[AMS Debug] ✗ priceDB is nil/invalid",
    LOG_DEBUG_NAME_BY_ID_FMT = "[AMS Debug] ✓ GetItemNameByID: %s",
    LOG_DEBUG_NAME_BY_ID_NIL = "[AMS Debug] ✗ GetItemNameByID: nil",
    LOG_DEBUG_ITEM_INFO_FMT = "[AMS Debug] ✓ GetItemInfo: %s",
    LOG_DEBUG_ITEM_INFO_NIL = "[AMS Debug] ✗ GetItemInfo: nil",
    LOG_DEBUG_END = "[AMS Debug] === End ===",
  },
  deDE = {
    APP_TITLE = "Auctionator Mini Suche (Retail)",
    OPTIONS_TITLE = "Auctionator Mini Suche - Optionen",
    STATUS_READY = "Bereit",
    STATUS_JOBS_ABORTED = "Jobs abgebrochen",
    STATUS_INDEX_BUILDING = "Index wird aufgebaut…",
    STATUS_NO_DATA_INDEXED = "Keine indizierten Daten",
    STATUS_NO_DATA = "Keine Daten",
    STATUS_NO_MATCHES = "Keine Treffer",
    STATUS_MATCHES_FOUND_FMT = "%d Treffer gefunden",
    STATUS_MATCHES_TOTAL_FMT = " (%d insgesamt, erhöhe Zeilenanzahl für mehr)",
    SEARCH_LABEL_FMT = "Itemname (mind. %d Zeichen)",
    BUTTON_SEARCH = "Suchen",
    BUTTON_CLEAR = "Clear",
    TOOLTIP_SEARCH = "Suchen",
    TOOLTIP_CLEAR = "Clear",
    TOOLTIP_OPTIONS = "Optionen",
    MINIMAP_TOOLTIP_TITLE = "Auctionator Mini Suche",
    MINIMAP_TOOLTIP_HINT = "Linksklick: Fenster öffnen/schließen\nZiehen: Icon verschieben",
    DEBUG_TOOLTIP_ACTIVE = "Debug-Modus aktiv",
    DEBUG_TOOLTIP_SCAN = "/ams scan verfügbar",
    DEBUG_TOOLTIP_ICON = "Icon: Wrench",
    RESET_CONFIRM_TEXT = "AuctionatorMiniSearch-Daten zurücksetzen?\n(Index, Missing-Liste und UI-Einstellungen werden gelöscht.)",
    RESET_BUTTON = "Reset",
    CANCEL_BUTTON = "Abbrechen",
    TAB_GENERAL = "Allgemein",
    TAB_SEARCH = "Suche",
    TAB_DATA = "Daten",
    SECTION_DISPLAY = "Anzeige",
    SECTION_SEARCH_BEHAVIOR = "Suchverhalten",
    SECTION_INDEX_STORAGE = "Index & Speicherung",
    OPTION_LIVE_SEARCH_LABEL = "Live-Suche beim Tippen",
    OPTION_LIVE_SEARCH_INFO = "Wenn aktiv, werden Treffer direkt beim Schreiben aktualisiert.",
    OPTION_MINIMAP_ICON_LABEL = "Minimap-Icon anzeigen",
    OPTION_MINIMAP_ICON_INFO = "Zeigt oder versteckt den AMS-Button an der Minimap.",
    OPTION_MIN_CHARS_LABEL = "Mindestzeichen",
    OPTION_MIN_CHARS_INFO = "Legt fest, ab wie vielen Zeichen eine Suche gestartet wird.",
    OPTION_KEEP_FOCUS_LABEL = "Fokus nach Enter behalten",
    OPTION_KEEP_FOCUS_INFO = "Wenn aktiv, bleibt der Cursor nach Enter im Suchfeld.",
    OPTION_DEBUG_LABEL = "Debug-Modus aktivieren",
    OPTION_DEBUG_INFO = "Erlaubt /ams scan und zeigt das Debug-Werkzeug-Icon im Hauptfenster an.",
    OPTION_STATUS_DETAIL_LABEL = "Detaillierte Statusmeldungen",
    OPTION_STATUS_DETAIL_INFO = "Bei AUS werden längere Fortschrittstexte auf kurze Meldungen reduziert.",
    OPTION_REFRESH_DAYS_LABEL = "Refresh ab Tagen",
    OPTION_REFRESH_DAYS_INFO = "Ab diesem Alter werden Preise im Hintergrund bevorzugt aktualisiert.",
    OPTION_AUTODELETE_DAYS_LABEL = "Auto-Löschen ab Tagen",
    OPTION_AUTODELETE_DAYS_INFO = "0 = aus. Ab diesem Alter werden Einträge beim Hintergrund-Refresh aus dem AMS-Index entfernt.",
    OPTION_REBUILD_INDEX_LABEL = "Index neu aufbauen",
    OPTION_REBUILD_INDEX_INFO = "Startet einen vollständigen Neuaufbau aus der aktuellen Auctionator-Datenbank.",
    OPTION_RESET_DATA_LABEL = "Daten zurücksetzen",
    OPTION_RESET_DATA_INFO = "Löscht gespeicherte AMS-Daten und erstellt einen frischen Index.",
    CACHE_HINT = "|cffccccccHinweis: Einige Items erscheinen erst in der Suche, nachdem sie im Spiel einmal gesehen wurden (WoW-Cache).|r",
    STATUS_NO_CHAT_EDITBOX = "Kein geöffneter Chat-Eingabebereich für Shift-Link.",
    FALLBACK_ITEM_FMT = "Item %d",
    PRICE_RANGE_PREFIX = "|cff66c0ffSpanne|r ",
    PRICE_RANGE_TO = " |cff66c0ffbis|r ",
    AGE_DAYS_FMT = "%d Tage",
    STATUS_PRICES_REFRESHING_BG = "Preise werden im Hintergrund aktualisiert...",
    STATUS_PRICES_UPDATED_FMT = "Preise aktualisiert: %d",
    STATUS_PRICES_UPDATED_REMOVED_FMT = "Preise aktualisiert: %d | veraltet entfernt: %d",
    STATUS_ZEROPRICE_CHECKING = "Zero-Preis Items werden geprüft...",
    STATUS_ZEROPRICE_UPDATED_FMT = "Zero-Preis Items aktualisiert: %d",
    STATUS_ZEROPRICE_CHECK_DONE_FMT = "Zero-Preis Check: %d geprüft",
    STATUS_INDEX_RECONCILING = "Index-Abgleich läuft...",
    STATUS_INDEX_RECONCILE_ADDED_FMT = "Index-Abgleich: %d neu hinzugefügt",
    STATUS_INDEX_COMPLETE = "Index vollständig",
    STATUS_INDEX_RECONCILE_PROGRESS_FMT = "Index-Abgleich: %d%% (%d neu)",
    STATUS_NO_MISSING_ITEMS_OPEN = "Keine fehlenden Items offen",
    STATUS_ADDING_MORE_PRICES_PROGRESS_FMT = "Weitere Preise werden in Datenbank hinzugefügt... [%d%%] Bitte warten!",
    STATUS_CHECKING_MISSING_PROGRESS_FMT = "Fehlende Items werden geprüft... [%d%%]",
    STATUS_MISSING_UPDATED_FMT = "Fehlende Items aktualisiert: %d neu, %d offen",
    STATUS_NO_MISSING_ITEMS = "Keine fehlenden Items",
    STATUS_CHECKING_MISSING = "Fehlende Items werden geprüft...",
    STATUS_CHECKING_MISSING_COUNT_FMT = "Fehlende Items werden geprüft (%d)...",
    ERROR_INVALID_PRICE_DB = "Auctionator-Preisdatenbank ungültig oder leer!",
    STATUS_INDEX_DB_SCANNING_PROGRESS_FMT = "Preis-Index-Datenbank wird durchsucht [%d%%] Bitte warten!",
    LOG_INDEX_FULLY_LOADED_FMT = "[AMS] Index vollständig geladen: %d Items",
    STATUS_RESET_REBUILDING = "SV zurückgesetzt. Index wird neu aufgebaut...",
    STATUS_SCAN_COOLDOWN_FMT = "Scan-Cooldown aktiv: noch %d Min",
    ERROR_NO_PRICE_DB_SCAN = "Keine Preisdatenbank vorhanden. Bitte Auctionator öffnen und einen Scan durchführen.",
    LOG_AUCTIONATOR_NOT_INSTALLED = "[AMS] Fehler: Das Addon 'Auctionator' ist nicht installiert oder aktiviert!",
    LOG_AUCTIONATOR_NOT_LOADED = "[AMS] Auctionator nicht geladen!",
    LOG_API_DETECTED = "[AMS] Auctionator API v1 erkannt.",
    LOG_API_NOT_FOUND_FALLBACK = "[AMS] Hinweis: Auctionator API v1 nicht gefunden, nutze DB-Fallback.",
    LOG_DB_NIL_API_ACTIVE = "[AMS] AUCTIONATOR_PRICE_DATABASE ist nil, API-Modus bleibt aktiv.",
    LOG_DB_NIL = "[AMS] AUCTIONATOR_PRICE_DATABASE ist nil!",
    LOG_DB_DESERIALIZE_ERROR = "[AMS] Fehler beim Deserialisieren der Preisdatenbank!",
    LOG_NO_PRICE_DATA_REALM_FMT = "[AMS] Keine Preisdaten für Realm: %s. Bitte Auctionator öffnen und einen Scan durchführen.",
    LOG_NO_PRICE_DATA_REALM_FACTION_FMT = "[AMS] Keine Preisdaten für Realm/Faction: %s",
    LOG_DB_LOADED = "[AMS] Datenbank geladen. Index wird beim Öffnen erstellt.",
    LOG_API_MODE_ACTIVE = "[AMS] API-Modus aktiv. Index wird beim Öffnen erstellt.",
    LOG_ERR_UI_NOT_LOADED = "[AMS] Fehler: UI wurde nicht geladen.",
    LOG_ERR_SEARCHBOX_NOT_INIT = "[AMS] Fehler: searchBox ist nicht initialisiert! Prüfe, ob UI.lua korrekt geladen wird und in der .toc ganz oben steht.",
    LOG_ERR_AUCTIONATOR_ADDON_INACTIVE = "[AMS] FEHLER: Auctionator-Addon ist nicht aktiviert!",
    LOG_SCAN_DEBUG_ONLY = "[AMS] /ams scan ist nur im Debug-Modus verfügbar.",
    LOG_SCAN_ALREADY_RUNNING = "[AMS] Scan läuft bereits.",
    LOG_MANUAL_SCAN_STARTED = "[AMS] Manueller Scan gestartet (Debug).",
    LOG_DEBUG_MODE_FMT = "[AMS] Debug-Modus: %s",
    STATE_ON = "AN",
    STATE_OFF = "AUS",
    LOG_DEBUG_INVALID_ITEMID_FMT = "[AMS Debug] Ungültige ItemID: %s",
    LOG_DEBUG_HEADER_ITEMID_FMT = "[AMS Debug] === ItemID %d ===",
    LOG_DEBUG_IN_SEARCHINDEX_FMT = "[AMS Debug] ✓ Im searchIndex: %s | Preis: %s | LastCheck: %s",
    LOG_DEBUG_NOT_IN_SEARCHINDEX = "[AMS Debug] ✗ NICHT im searchIndex",
    LOG_DEBUG_IN_MISSING_FMT = "[AMS Debug] ⚠ In missingItems (Retry: %d)",
    LOG_DEBUG_NOT_IN_MISSING = "[AMS Debug] ✓ NICHT in missingItems",
    LOG_DEBUG_API_PRICE_FMT = "[AMS Debug] ✓ API Preis: %s",
    LOG_DEBUG_API_PRICE_NIL = "[AMS Debug] ✗ API Preis: nil",
    LOG_DEBUG_IN_PRICEDB_FMT = "[AMS Debug] ✓ In priceDB Key '%s' | Preis: %s",
    LOG_DEBUG_NOT_IN_PRICEDB = "[AMS Debug] ✗ NICHT in priceDB gefunden",
    LOG_DEBUG_PRICEDB_INVALID = "[AMS Debug] ✗ priceDB ist nil/ungültig",
    LOG_DEBUG_NAME_BY_ID_FMT = "[AMS Debug] ✓ GetItemNameByID: %s",
    LOG_DEBUG_NAME_BY_ID_NIL = "[AMS Debug] ✗ GetItemNameByID: nil",
    LOG_DEBUG_ITEM_INFO_FMT = "[AMS Debug] ✓ GetItemInfo: %s",
    LOG_DEBUG_ITEM_INFO_NIL = "[AMS Debug] ✗ GetItemInfo: nil",
    LOG_DEBUG_END = "[AMS Debug] === Ende ===",
  },
  frFR = {
    APP_TITLE = "Auctionator Mini Search (Retail)",
    OPTIONS_TITLE = "Auctionator Mini Search - Options",
    STATUS_READY = "Pret",
    STATUS_JOBS_ABORTED = "Taches annulees",
    STATUS_INDEX_BUILDING = "Construction de l'index...",
    STATUS_NO_DATA_INDEXED = "Aucune donnee indexee",
    STATUS_NO_DATA = "Aucune donnee",
    STATUS_NO_MATCHES = "Aucun resultat",
    STATUS_MATCHES_FOUND_FMT = "%d resultats trouves",
    STATUS_MATCHES_TOTAL_FMT = " (%d au total, augmentez le nombre de lignes pour en voir plus)",
    SEARCH_LABEL_FMT = "Nom de l'objet (min. %d caracteres)",
    BUTTON_SEARCH = "Rechercher",
    BUTTON_CLEAR = "Effacer",
    TOOLTIP_SEARCH = "Rechercher",
    TOOLTIP_CLEAR = "Effacer",
    TOOLTIP_OPTIONS = "Options",
    MINIMAP_TOOLTIP_TITLE = "Auctionator Mini Search",
    MINIMAP_TOOLTIP_HINT = "Clic gauche: Ouvrir/fermer la fenetre\nGlisser: Deplacer l'icone",
    DEBUG_TOOLTIP_ACTIVE = "Mode debug actif",
    DEBUG_TOOLTIP_SCAN = "/ams scan disponible",
    DEBUG_TOOLTIP_ICON = "Icone: Cle",
    RESET_CONFIRM_TEXT = "Reinitialiser les donnees AuctionatorMiniSearch?\n(L'index, la liste manquante et les parametres UI seront supprimes.)",
    RESET_BUTTON = "Reinitialiser",
    CANCEL_BUTTON = "Annuler",
    TAB_GENERAL = "General",
    TAB_SEARCH = "Recherche",
    TAB_DATA = "Donnees",
    SECTION_DISPLAY = "Affichage",
    SECTION_SEARCH_BEHAVIOR = "Comportement de recherche",
    SECTION_INDEX_STORAGE = "Index et stockage",
    OPTION_LIVE_SEARCH_LABEL = "Recherche en direct pendant la saisie",
    OPTION_LIVE_SEARCH_INFO = "Si active, les resultats se mettent a jour pendant la saisie.",
    OPTION_MINIMAP_ICON_LABEL = "Afficher l'icone de minimap",
    OPTION_MINIMAP_ICON_INFO = "Affiche ou masque le bouton AMS sur la minimap.",
    OPTION_MIN_CHARS_LABEL = "Caracteres minimum",
    OPTION_MIN_CHARS_INFO = "Definit a partir de combien de caracteres la recherche demarre.",
    OPTION_KEEP_FOCUS_LABEL = "Conserver le focus apres Entree",
    OPTION_KEEP_FOCUS_INFO = "Si active, le curseur reste dans le champ de recherche apres Entree.",
    OPTION_DEBUG_LABEL = "Activer le mode debug",
    OPTION_DEBUG_INFO = "Autorise /ams scan et affiche l'icone debug dans la fenetre principale.",
    OPTION_STATUS_DETAIL_LABEL = "Messages d'etat detailles",
    OPTION_STATUS_DETAIL_INFO = "Si DESACTIVE, les longs messages de progression sont raccourcis.",
    OPTION_REFRESH_DAYS_LABEL = "Actualiser apres (jours)",
    OPTION_REFRESH_DAYS_INFO = "A partir de cet age, les prix sont actualises en arriere-plan.",
    OPTION_AUTODELETE_DAYS_LABEL = "Suppression auto apres (jours)",
    OPTION_AUTODELETE_DAYS_INFO = "0 = desactive. A partir de cet age, les entrees sont supprimees de l'index AMS pendant l'actualisation.",
    OPTION_REBUILD_INDEX_LABEL = "Reconstruire l'index",
    OPTION_REBUILD_INDEX_INFO = "Lance une reconstruction complete a partir de la base Auctionator actuelle.",
    OPTION_RESET_DATA_LABEL = "Reinitialiser les donnees",
    OPTION_RESET_DATA_INFO = "Supprime les donnees AMS stockees et cree un index neuf.",
    CACHE_HINT = "|cffccccccNote: Certains objets n'apparaissent dans la recherche qu'apres avoir ete vus une fois en jeu (cache WoW).|r",
    STATUS_NO_CHAT_EDITBOX = "Aucune zone de chat ouverte pour inserer le lien avec Shift.",
    FALLBACK_ITEM_FMT = "Objet %d",
    PRICE_RANGE_PREFIX = "|cff66c0ffPlage|r ",
    PRICE_RANGE_TO = " |cff66c0ffa|r ",
    AGE_DAYS_FMT = "%d jours",
    STATUS_PRICES_REFRESHING_BG = "Actualisation des prix en arriere-plan...",
    STATUS_PRICES_UPDATED_FMT = "Prix mis a jour: %d",
    STATUS_PRICES_UPDATED_REMOVED_FMT = "Prix mis a jour: %d | obsoletes supprimes: %d",
    STATUS_ZEROPRICE_CHECKING = "Verification des objets a prix zero...",
    STATUS_ZEROPRICE_UPDATED_FMT = "Objets a prix zero mis a jour: %d",
    STATUS_ZEROPRICE_CHECK_DONE_FMT = "Verification prix zero: %d verifies",
    STATUS_INDEX_RECONCILING = "Synchronisation de l'index...",
    STATUS_INDEX_RECONCILE_ADDED_FMT = "Synchronisation index: %d ajoutes",
    STATUS_INDEX_COMPLETE = "Index termine",
    STATUS_INDEX_RECONCILE_PROGRESS_FMT = "Synchronisation index: %d%% (%d nouveaux)",
    STATUS_NO_MISSING_ITEMS_OPEN = "Aucun objet manquant ouvert",
    STATUS_ADDING_MORE_PRICES_PROGRESS_FMT = "Ajout de prix supplementaires a la base... [%d%%] Patientez!",
    STATUS_CHECKING_MISSING_PROGRESS_FMT = "Verification des objets manquants... [%d%%]",
    STATUS_MISSING_UPDATED_FMT = "Objets manquants mis a jour: %d nouveaux, %d ouverts",
    STATUS_NO_MISSING_ITEMS = "Aucun objet manquant",
    STATUS_CHECKING_MISSING = "Verification des objets manquants...",
    STATUS_CHECKING_MISSING_COUNT_FMT = "Verification des objets manquants (%d)...",
    ERROR_INVALID_PRICE_DB = "Base de prix Auctionator invalide ou vide!",
    STATUS_INDEX_DB_SCANNING_PROGRESS_FMT = "Analyse de la base d'index de prix [%d%%] Patientez!",
    LOG_INDEX_FULLY_LOADED_FMT = "[AMS] Index complet charge: %d objets",
    STATUS_RESET_REBUILDING = "SavedVariables reinitialisees. Reconstruction de l'index...",
    STATUS_SCAN_COOLDOWN_FMT = "Cooldown de scan actif: %d min restantes",
    ERROR_NO_PRICE_DB_SCAN = "Aucune base de prix disponible. Ouvrez Auctionator et lancez un scan.",
    LOG_AUCTIONATOR_NOT_INSTALLED = "[AMS] Erreur: L'addon 'Auctionator' n'est pas installe ou active!",
    LOG_AUCTIONATOR_NOT_LOADED = "[AMS] Auctionator non charge!",
    LOG_API_DETECTED = "[AMS] API Auctionator v1 detectee.",
    LOG_API_NOT_FOUND_FALLBACK = "[AMS] Info: API Auctionator v1 introuvable, fallback base de donnees actif.",
    LOG_DB_NIL_API_ACTIVE = "[AMS] AUCTIONATOR_PRICE_DATABASE est nil, mode API actif.",
    LOG_DB_NIL = "[AMS] AUCTIONATOR_PRICE_DATABASE est nil!",
    LOG_DB_DESERIALIZE_ERROR = "[AMS] Erreur lors de la deserialisation de la base de prix!",
    LOG_NO_PRICE_DATA_REALM_FMT = "[AMS] Aucune donnee de prix pour le royaume: %s. Ouvrez Auctionator et lancez un scan.",
    LOG_NO_PRICE_DATA_REALM_FACTION_FMT = "[AMS] Aucune donnee de prix pour royaume/faction: %s",
    LOG_DB_LOADED = "[AMS] Base chargee. L'index sera construit a l'ouverture.",
    LOG_API_MODE_ACTIVE = "[AMS] Mode API actif. L'index sera construit a l'ouverture.",
    LOG_ERR_UI_NOT_LOADED = "[AMS] Erreur: L'interface n'a pas ete chargee.",
    LOG_ERR_SEARCHBOX_NOT_INIT = "[AMS] Erreur: searchBox non initialise! Verifiez le chargement de UI.lua et son ordre avant Core dans le .toc.",
    LOG_ERR_AUCTIONATOR_ADDON_INACTIVE = "[AMS] ERREUR: L'addon Auctionator n'est pas active!",
    LOG_SCAN_DEBUG_ONLY = "[AMS] /ams scan est disponible uniquement en mode debug.",
    LOG_SCAN_ALREADY_RUNNING = "[AMS] Un scan est deja en cours.",
    LOG_MANUAL_SCAN_STARTED = "[AMS] Scan manuel lance (debug).",
    LOG_DEBUG_MODE_FMT = "[AMS] Mode debug: %s",
    STATE_ON = "ON",
    STATE_OFF = "OFF",
    LOG_DEBUG_INVALID_ITEMID_FMT = "[AMS Debug] ItemID invalide: %s",
    LOG_DEBUG_HEADER_ITEMID_FMT = "[AMS Debug] === ItemID %d ===",
    LOG_DEBUG_IN_SEARCHINDEX_FMT = "[AMS Debug] ✓ Present dans searchIndex: %s | Prix: %s | Dernier controle: %s",
    LOG_DEBUG_NOT_IN_SEARCHINDEX = "[AMS Debug] ✗ ABSENT de searchIndex",
    LOG_DEBUG_IN_MISSING_FMT = "[AMS Debug] ⚠ Dans missingItems (Retry: %d)",
    LOG_DEBUG_NOT_IN_MISSING = "[AMS Debug] ✓ ABSENT de missingItems",
    LOG_DEBUG_API_PRICE_FMT = "[AMS Debug] ✓ Prix API: %s",
    LOG_DEBUG_API_PRICE_NIL = "[AMS Debug] ✗ Prix API: nil",
    LOG_DEBUG_IN_PRICEDB_FMT = "[AMS Debug] ✓ Dans priceDB cle '%s' | Prix: %s",
    LOG_DEBUG_NOT_IN_PRICEDB = "[AMS Debug] ✗ Introuvable dans priceDB",
    LOG_DEBUG_PRICEDB_INVALID = "[AMS Debug] ✗ priceDB est nil/invalide",
    LOG_DEBUG_NAME_BY_ID_FMT = "[AMS Debug] ✓ GetItemNameByID: %s",
    LOG_DEBUG_NAME_BY_ID_NIL = "[AMS Debug] ✗ GetItemNameByID: nil",
    LOG_DEBUG_ITEM_INFO_FMT = "[AMS Debug] ✓ GetItemInfo: %s",
    LOG_DEBUG_ITEM_INFO_NIL = "[AMS Debug] ✗ GetItemInfo: nil",
    LOG_DEBUG_END = "[AMS Debug] === Fin ===",
  },
  esES = {
    APP_TITLE = "Auctionator Mini Search (Retail)",
    OPTIONS_TITLE = "Auctionator Mini Search - Opciones",
    STATUS_READY = "Listo",
    STATUS_JOBS_ABORTED = "Tareas canceladas",
    STATUS_INDEX_BUILDING = "Construyendo indice...",
    STATUS_NO_DATA_INDEXED = "Sin datos indexados",
    STATUS_NO_DATA = "Sin datos",
    STATUS_NO_MATCHES = "Sin resultados",
    STATUS_MATCHES_FOUND_FMT = "%d resultados encontrados",
    STATUS_MATCHES_TOTAL_FMT = " (%d en total, aumenta las filas para ver mas)",
    SEARCH_LABEL_FMT = "Nombre del objeto (min. %d caracteres)",
    BUTTON_SEARCH = "Buscar",
    BUTTON_CLEAR = "Limpiar",
    TOOLTIP_SEARCH = "Buscar",
    TOOLTIP_CLEAR = "Limpiar",
    TOOLTIP_OPTIONS = "Opciones",
    MINIMAP_TOOLTIP_TITLE = "Auctionator Mini Search",
    MINIMAP_TOOLTIP_HINT = "Clic izquierdo: abrir/cerrar ventana\nArrastrar: mover icono",
    DEBUG_TOOLTIP_ACTIVE = "Modo depuracion activo",
    DEBUG_TOOLTIP_SCAN = "/ams scan disponible",
    DEBUG_TOOLTIP_ICON = "Icono: Llave",
    RESET_CONFIRM_TEXT = "Restablecer datos de AuctionatorMiniSearch?\n(Se borraran indice, lista de faltantes y ajustes de UI.)",
    RESET_BUTTON = "Restablecer",
    CANCEL_BUTTON = "Cancelar",
    TAB_GENERAL = "General",
    TAB_SEARCH = "Busqueda",
    TAB_DATA = "Datos",
    SECTION_DISPLAY = "Visualizacion",
    SECTION_SEARCH_BEHAVIOR = "Comportamiento de busqueda",
    SECTION_INDEX_STORAGE = "Indice y almacenamiento",
    OPTION_LIVE_SEARCH_LABEL = "Busqueda en vivo al escribir",
    OPTION_LIVE_SEARCH_INFO = "Si esta activado, los resultados se actualizan mientras escribes.",
    OPTION_MINIMAP_ICON_LABEL = "Mostrar icono del minimapa",
    OPTION_MINIMAP_ICON_INFO = "Muestra u oculta el boton de AMS en el minimapa.",
    OPTION_MIN_CHARS_LABEL = "Caracteres minimos",
    OPTION_MIN_CHARS_INFO = "Define a partir de cuantos caracteres inicia la busqueda.",
    OPTION_KEEP_FOCUS_LABEL = "Mantener foco tras Enter",
    OPTION_KEEP_FOCUS_INFO = "Si esta activado, el cursor permanece en la caja de busqueda tras Enter.",
    OPTION_DEBUG_LABEL = "Activar modo depuracion",
    OPTION_DEBUG_INFO = "Permite /ams scan y muestra el icono de depuracion en la ventana principal.",
    OPTION_STATUS_DETAIL_LABEL = "Mensajes de estado detallados",
    OPTION_STATUS_DETAIL_INFO = "Si esta DESACTIVADO, los mensajes largos de progreso se acortan.",
    OPTION_REFRESH_DAYS_LABEL = "Actualizar despues de dias",
    OPTION_REFRESH_DAYS_INFO = "A partir de esta antiguedad, los precios se actualizan en segundo plano.",
    OPTION_AUTODELETE_DAYS_LABEL = "Autoeliminar despues de dias",
    OPTION_AUTODELETE_DAYS_INFO = "0 = desactivado. A partir de esta antiguedad, las entradas se eliminan del indice AMS durante la actualizacion.",
    OPTION_REBUILD_INDEX_LABEL = "Reconstruir indice",
    OPTION_REBUILD_INDEX_INFO = "Inicia una reconstruccion completa desde la base de datos actual de Auctionator.",
    OPTION_RESET_DATA_LABEL = "Restablecer datos",
    OPTION_RESET_DATA_INFO = "Elimina datos guardados de AMS y crea un indice nuevo.",
    CACHE_HINT = "|cffccccccNota: Algunos objetos solo aparecen en la busqueda despues de haber sido vistos una vez en el juego (cache de WoW).|r",
    STATUS_NO_CHAT_EDITBOX = "No hay una caja de chat abierta para insertar el enlace con Shift.",
    FALLBACK_ITEM_FMT = "Objeto %d",
    PRICE_RANGE_PREFIX = "|cff66c0ffRango|r ",
    PRICE_RANGE_TO = " |cff66c0ffa|r ",
    AGE_DAYS_FMT = "%d dias",
    STATUS_PRICES_REFRESHING_BG = "Actualizando precios en segundo plano...",
    STATUS_PRICES_UPDATED_FMT = "Precios actualizados: %d",
    STATUS_PRICES_UPDATED_REMOVED_FMT = "Precios actualizados: %d | obsoletos eliminados: %d",
    STATUS_ZEROPRICE_CHECKING = "Comprobando objetos con precio cero...",
    STATUS_ZEROPRICE_UPDATED_FMT = "Objetos con precio cero actualizados: %d",
    STATUS_ZEROPRICE_CHECK_DONE_FMT = "Revision precio cero: %d comprobados",
    STATUS_INDEX_RECONCILING = "Reconciliando indice...",
    STATUS_INDEX_RECONCILE_ADDED_FMT = "Reconciliacion indice: %d nuevos",
    STATUS_INDEX_COMPLETE = "Indice completo",
    STATUS_INDEX_RECONCILE_PROGRESS_FMT = "Reconciliacion indice: %d%% (%d nuevos)",
    STATUS_NO_MISSING_ITEMS_OPEN = "No hay objetos faltantes abiertos",
    STATUS_ADDING_MORE_PRICES_PROGRESS_FMT = "Anadiendo mas precios a la base de datos... [%d%%] Espera!",
    STATUS_CHECKING_MISSING_PROGRESS_FMT = "Comprobando objetos faltantes... [%d%%]",
    STATUS_MISSING_UPDATED_FMT = "Faltantes actualizados: %d nuevos, %d abiertos",
    STATUS_NO_MISSING_ITEMS = "Sin objetos faltantes",
    STATUS_CHECKING_MISSING = "Comprobando objetos faltantes...",
    STATUS_CHECKING_MISSING_COUNT_FMT = "Comprobando objetos faltantes (%d)...",
    ERROR_INVALID_PRICE_DB = "Base de datos de precios de Auctionator invalida o vacia!",
    STATUS_INDEX_DB_SCANNING_PROGRESS_FMT = "Escaneando base de datos del indice de precios [%d%%] Espera!",
    LOG_INDEX_FULLY_LOADED_FMT = "[AMS] Indice completamente cargado: %d objetos",
    STATUS_RESET_REBUILDING = "SavedVariables restablecidas. Reconstruyendo indice...",
    STATUS_SCAN_COOLDOWN_FMT = "Enfriamiento de escaneo activo: %d min restantes",
    ERROR_NO_PRICE_DB_SCAN = "No hay base de precios disponible. Abre Auctionator y ejecuta un escaneo.",
    LOG_AUCTIONATOR_NOT_INSTALLED = "[AMS] Error: El addon 'Auctionator' no esta instalado o activado!",
    LOG_AUCTIONATOR_NOT_LOADED = "[AMS] Auctionator no cargado!",
    LOG_API_DETECTED = "[AMS] API de Auctionator v1 detectada.",
    LOG_API_NOT_FOUND_FALLBACK = "[AMS] Aviso: API v1 de Auctionator no encontrada, usando fallback de BD.",
    LOG_DB_NIL_API_ACTIVE = "[AMS] AUCTIONATOR_PRICE_DATABASE es nil, el modo API sigue activo.",
    LOG_DB_NIL = "[AMS] AUCTIONATOR_PRICE_DATABASE es nil!",
    LOG_DB_DESERIALIZE_ERROR = "[AMS] Error al deserializar la base de datos de precios!",
    LOG_NO_PRICE_DATA_REALM_FMT = "[AMS] Sin datos de precios para el reino: %s. Abre Auctionator y ejecuta un escaneo.",
    LOG_NO_PRICE_DATA_REALM_FACTION_FMT = "[AMS] Sin datos de precios para reino/faccion: %s",
    LOG_DB_LOADED = "[AMS] Base de datos cargada. El indice se construira al abrir.",
    LOG_API_MODE_ACTIVE = "[AMS] Modo API activo. El indice se construira al abrir.",
    LOG_ERR_UI_NOT_LOADED = "[AMS] Error: La interfaz no se cargo.",
    LOG_ERR_SEARCHBOX_NOT_INIT = "[AMS] Error: searchBox no inicializado! Comprueba que UI.lua se carga correctamente y antes de Core en el .toc.",
    LOG_ERR_AUCTIONATOR_ADDON_INACTIVE = "[AMS] ERROR: El addon Auctionator no esta activado!",
    LOG_SCAN_DEBUG_ONLY = "[AMS] /ams scan solo esta disponible en modo depuracion.",
    LOG_SCAN_ALREADY_RUNNING = "[AMS] Ya hay un escaneo en curso.",
    LOG_MANUAL_SCAN_STARTED = "[AMS] Escaneo manual iniciado (debug).",
    LOG_DEBUG_MODE_FMT = "[AMS] Modo depuracion: %s",
    STATE_ON = "ON",
    STATE_OFF = "OFF",
    LOG_DEBUG_INVALID_ITEMID_FMT = "[AMS Debug] ItemID invalido: %s",
    LOG_DEBUG_HEADER_ITEMID_FMT = "[AMS Debug] === ItemID %d ===",
    LOG_DEBUG_IN_SEARCHINDEX_FMT = "[AMS Debug] ✓ En searchIndex: %s | Precio: %s | Ultima revision: %s",
    LOG_DEBUG_NOT_IN_SEARCHINDEX = "[AMS Debug] ✗ NO esta en searchIndex",
    LOG_DEBUG_IN_MISSING_FMT = "[AMS Debug] ⚠ En missingItems (Retry: %d)",
    LOG_DEBUG_NOT_IN_MISSING = "[AMS Debug] ✓ NO esta en missingItems",
    LOG_DEBUG_API_PRICE_FMT = "[AMS Debug] ✓ Precio API: %s",
    LOG_DEBUG_API_PRICE_NIL = "[AMS Debug] ✗ Precio API: nil",
    LOG_DEBUG_IN_PRICEDB_FMT = "[AMS Debug] ✓ En priceDB clave '%s' | Precio: %s",
    LOG_DEBUG_NOT_IN_PRICEDB = "[AMS Debug] ✗ NO encontrado en priceDB",
    LOG_DEBUG_PRICEDB_INVALID = "[AMS Debug] ✗ priceDB es nil/invalido",
    LOG_DEBUG_NAME_BY_ID_FMT = "[AMS Debug] ✓ GetItemNameByID: %s",
    LOG_DEBUG_NAME_BY_ID_NIL = "[AMS Debug] ✗ GetItemNameByID: nil",
    LOG_DEBUG_ITEM_INFO_FMT = "[AMS Debug] ✓ GetItemInfo: %s",
    LOG_DEBUG_ITEM_INFO_NIL = "[AMS Debug] ✗ GetItemInfo: nil",
    LOG_DEBUG_END = "[AMS Debug] === Fin ===",
  },
  ruRU = {
    APP_TITLE = "Auctionator Mini Search (Retail)",
    OPTIONS_TITLE = "Auctionator Mini Search - Настройки",
    STATUS_READY = "Готово",
    STATUS_JOBS_ABORTED = "Задачи отменены",
    STATUS_INDEX_BUILDING = "Построение индекса...",
    STATUS_NO_DATA_INDEXED = "Нет индексированных данных",
    STATUS_NO_DATA = "Нет данных",
    STATUS_NO_MATCHES = "Совпадений нет",
    STATUS_MATCHES_FOUND_FMT = "Найдено совпадений: %d",
    STATUS_MATCHES_TOTAL_FMT = " (всего %d, увеличьте число строк для показа)",
    SEARCH_LABEL_FMT = "Название предмета (мин. %d символа)",
    BUTTON_SEARCH = "Поиск",
    BUTTON_CLEAR = "Очистить",
    TOOLTIP_SEARCH = "Поиск",
    TOOLTIP_CLEAR = "Очистить",
    TOOLTIP_OPTIONS = "Настройки",
    MINIMAP_TOOLTIP_TITLE = "Auctionator Mini Search",
    MINIMAP_TOOLTIP_HINT = "ЛКМ: Открыть/закрыть окно\nПеретаскивание: Переместить иконку",
    DEBUG_TOOLTIP_ACTIVE = "Режим отладки активен",
    DEBUG_TOOLTIP_SCAN = "/ams scan доступно",
    DEBUG_TOOLTIP_ICON = "Иконка: Гаечный ключ",
    RESET_CONFIRM_TEXT = "Сбросить данные AuctionatorMiniSearch?\n(Индекс, список отсутствующих и настройки интерфейса будут удалены.)",
    RESET_BUTTON = "Сброс",
    CANCEL_BUTTON = "Отмена",
    TAB_GENERAL = "Общее",
    TAB_SEARCH = "Поиск",
    TAB_DATA = "Данные",
    SECTION_DISPLAY = "Отображение",
    SECTION_SEARCH_BEHAVIOR = "Поведение поиска",
    SECTION_INDEX_STORAGE = "Индекс и хранилище",
    OPTION_LIVE_SEARCH_LABEL = "Живой поиск при наборе",
    OPTION_LIVE_SEARCH_INFO = "Если включено, результаты обновляются во время ввода.",
    OPTION_MINIMAP_ICON_LABEL = "Показывать иконку на миникарте",
    OPTION_MINIMAP_ICON_INFO = "Показывает или скрывает кнопку AMS на миникарте.",
    OPTION_MIN_CHARS_LABEL = "Минимум символов",
    OPTION_MIN_CHARS_INFO = "Определяет, с какого количества символов запускать поиск.",
    OPTION_KEEP_FOCUS_LABEL = "Оставлять фокус после Enter",
    OPTION_KEEP_FOCUS_INFO = "Если включено, курсор остается в поле поиска после Enter.",
    OPTION_DEBUG_LABEL = "Включить режим отладки",
    OPTION_DEBUG_INFO = "Разрешает /ams scan и показывает иконку отладки в главном окне.",
    OPTION_STATUS_DETAIL_LABEL = "Подробные статус-сообщения",
    OPTION_STATUS_DETAIL_INFO = "Если ВЫКЛ, длинные сообщения прогресса сокращаются.",
    OPTION_REFRESH_DAYS_LABEL = "Обновлять через (дней)",
    OPTION_REFRESH_DAYS_INFO = "Начиная с этого возраста цены обновляются в фоне.",
    OPTION_AUTODELETE_DAYS_LABEL = "Автоудаление через (дней)",
    OPTION_AUTODELETE_DAYS_INFO = "0 = выкл. Начиная с этого возраста записи удаляются из индекса AMS при фоновом обновлении.",
    OPTION_REBUILD_INDEX_LABEL = "Пересобрать индекс",
    OPTION_REBUILD_INDEX_INFO = "Запускает полную перестройку из текущей базы Auctionator.",
    OPTION_RESET_DATA_LABEL = "Сбросить данные",
    OPTION_RESET_DATA_INFO = "Удаляет сохраненные данные AMS и создает новый индекс.",
    CACHE_HINT = "|cffccccccПримечание: Некоторые предметы появляются в поиске только после того, как были хотя бы раз увидены в игре (кэш WoW).|r",
    STATUS_NO_CHAT_EDITBOX = "Нет открытого поля чата для вставки Shift-ссылки.",
    FALLBACK_ITEM_FMT = "Предмет %d",
    PRICE_RANGE_PREFIX = "|cff66c0ffДиапазон|r ",
    PRICE_RANGE_TO = " |cff66c0ffдо|r ",
    AGE_DAYS_FMT = "%d дн.",
    STATUS_PRICES_REFRESHING_BG = "Обновление цен в фоне...",
    STATUS_PRICES_UPDATED_FMT = "Цены обновлены: %d",
    STATUS_PRICES_UPDATED_REMOVED_FMT = "Цены обновлены: %d | устаревшие удалены: %d",
    STATUS_ZEROPRICE_CHECKING = "Проверка предметов с нулевой ценой...",
    STATUS_ZEROPRICE_UPDATED_FMT = "Предметы с нулевой ценой обновлены: %d",
    STATUS_ZEROPRICE_CHECK_DONE_FMT = "Проверка нулевой цены: %d проверено",
    STATUS_INDEX_RECONCILING = "Сверка индекса...",
    STATUS_INDEX_RECONCILE_ADDED_FMT = "Сверка индекса: добавлено %d",
    STATUS_INDEX_COMPLETE = "Индекс готов",
    STATUS_INDEX_RECONCILE_PROGRESS_FMT = "Сверка индекса: %d%% (%d новых)",
    STATUS_NO_MISSING_ITEMS_OPEN = "Нет открытых отсутствующих предметов",
    STATUS_ADDING_MORE_PRICES_PROGRESS_FMT = "Добавление дополнительных цен в базу... [%d%%] Подождите!",
    STATUS_CHECKING_MISSING_PROGRESS_FMT = "Проверка отсутствующих предметов... [%d%%]",
    STATUS_MISSING_UPDATED_FMT = "Отсутствующие обновлены: %d новых, %d осталось",
    STATUS_NO_MISSING_ITEMS = "Нет отсутствующих предметов",
    STATUS_CHECKING_MISSING = "Проверка отсутствующих предметов...",
    STATUS_CHECKING_MISSING_COUNT_FMT = "Проверка отсутствующих предметов (%d)...",
    ERROR_INVALID_PRICE_DB = "База цен Auctionator недействительна или пуста!",
    STATUS_INDEX_DB_SCANNING_PROGRESS_FMT = "Сканирование базы ценового индекса [%d%%] Подождите!",
    LOG_INDEX_FULLY_LOADED_FMT = "[AMS] Индекс полностью загружен: %d предметов",
    STATUS_RESET_REBUILDING = "SavedVariables сброшены. Пересборка индекса...",
    STATUS_SCAN_COOLDOWN_FMT = "Кулдаун сканирования активен: осталось %d мин",
    ERROR_NO_PRICE_DB_SCAN = "База цен недоступна. Откройте Auctionator и выполните сканирование.",
    LOG_AUCTIONATOR_NOT_INSTALLED = "[AMS] Ошибка: Аддон 'Auctionator' не установлен или отключен!",
    LOG_AUCTIONATOR_NOT_LOADED = "[AMS] Auctionator не загружен!",
    LOG_API_DETECTED = "[AMS] Обнаружен Auctionator API v1.",
    LOG_API_NOT_FOUND_FALLBACK = "[AMS] Внимание: Auctionator API v1 не найден, используется fallback базы данных.",
    LOG_DB_NIL_API_ACTIVE = "[AMS] AUCTIONATOR_PRICE_DATABASE = nil, режим API остается активным.",
    LOG_DB_NIL = "[AMS] AUCTIONATOR_PRICE_DATABASE = nil!",
    LOG_DB_DESERIALIZE_ERROR = "[AMS] Ошибка при десериализации базы цен!",
    LOG_NO_PRICE_DATA_REALM_FMT = "[AMS] Нет данных цен для мира: %s. Откройте Auctionator и выполните сканирование.",
    LOG_NO_PRICE_DATA_REALM_FACTION_FMT = "[AMS] Нет данных цен для мира/фракции: %s",
    LOG_DB_LOADED = "[AMS] База загружена. Индекс будет построен при открытии.",
    LOG_API_MODE_ACTIVE = "[AMS] Режим API активен. Индекс будет построен при открытии.",
    LOG_ERR_UI_NOT_LOADED = "[AMS] Ошибка: Интерфейс не загружен.",
    LOG_ERR_SEARCHBOX_NOT_INIT = "[AMS] Ошибка: searchBox не инициализирован! Проверьте загрузку UI.lua и порядок до Core в .toc.",
    LOG_ERR_AUCTIONATOR_ADDON_INACTIVE = "[AMS] ОШИБКА: Аддон Auctionator отключен!",
    LOG_SCAN_DEBUG_ONLY = "[AMS] /ams scan доступен только в режиме отладки.",
    LOG_SCAN_ALREADY_RUNNING = "[AMS] Сканирование уже выполняется.",
    LOG_MANUAL_SCAN_STARTED = "[AMS] Ручное сканирование запущено (debug).",
    LOG_DEBUG_MODE_FMT = "[AMS] Режим отладки: %s",
    STATE_ON = "ON",
    STATE_OFF = "OFF",
    LOG_DEBUG_INVALID_ITEMID_FMT = "[AMS Debug] Неверный itemID: %s",
    LOG_DEBUG_HEADER_ITEMID_FMT = "[AMS Debug] === ItemID %d ===",
    LOG_DEBUG_IN_SEARCHINDEX_FMT = "[AMS Debug] ✓ В searchIndex: %s | Цена: %s | Последняя проверка: %s",
    LOG_DEBUG_NOT_IN_SEARCHINDEX = "[AMS Debug] ✗ НЕТ в searchIndex",
    LOG_DEBUG_IN_MISSING_FMT = "[AMS Debug] ⚠ В missingItems (Retry: %d)",
    LOG_DEBUG_NOT_IN_MISSING = "[AMS Debug] ✓ НЕТ в missingItems",
    LOG_DEBUG_API_PRICE_FMT = "[AMS Debug] ✓ Цена API: %s",
    LOG_DEBUG_API_PRICE_NIL = "[AMS Debug] ✗ Цена API: nil",
    LOG_DEBUG_IN_PRICEDB_FMT = "[AMS Debug] ✓ В priceDB ключ '%s' | Цена: %s",
    LOG_DEBUG_NOT_IN_PRICEDB = "[AMS Debug] ✗ НЕ найдено в priceDB",
    LOG_DEBUG_PRICEDB_INVALID = "[AMS Debug] ✗ priceDB = nil/некорректна",
    LOG_DEBUG_NAME_BY_ID_FMT = "[AMS Debug] ✓ GetItemNameByID: %s",
    LOG_DEBUG_NAME_BY_ID_NIL = "[AMS Debug] ✗ GetItemNameByID: nil",
    LOG_DEBUG_ITEM_INFO_FMT = "[AMS Debug] ✓ GetItemInfo: %s",
    LOG_DEBUG_ITEM_INFO_NIL = "[AMS Debug] ✗ GetItemInfo: nil",
    LOG_DEBUG_END = "[AMS Debug] === Конец ===",
  },
  itIT = {
    APP_TITLE = "Auctionator Mini Search (Retail)",
    OPTIONS_TITLE = "Auctionator Mini Search - Opzioni",
    STATUS_READY = "Pronto",
    STATUS_JOBS_ABORTED = "Processi annullati",
    STATUS_INDEX_BUILDING = "Costruzione indice...",
    STATUS_NO_DATA_INDEXED = "Nessun dato indicizzato",
    STATUS_NO_DATA = "Nessun dato",
    STATUS_NO_MATCHES = "Nessun risultato",
    STATUS_MATCHES_FOUND_FMT = "%d risultati trovati",
    STATUS_MATCHES_TOTAL_FMT = " (%d totali, aumenta il numero di righe per vederne di piu)",
    SEARCH_LABEL_FMT = "Nome oggetto (min. %d caratteri)",
    BUTTON_SEARCH = "Cerca",
    BUTTON_CLEAR = "Pulisci",
    TOOLTIP_SEARCH = "Cerca",
    TOOLTIP_CLEAR = "Pulisci",
    TOOLTIP_OPTIONS = "Opzioni",
    MINIMAP_TOOLTIP_TITLE = "Auctionator Mini Search",
    MINIMAP_TOOLTIP_HINT = "Click sinistro: Apri/chiudi finestra\nTrascina: Sposta icona",
    DEBUG_TOOLTIP_ACTIVE = "Modalita debug attiva",
    DEBUG_TOOLTIP_SCAN = "/ams scan disponibile",
    DEBUG_TOOLTIP_ICON = "Icona: Chiave inglese",
    RESET_CONFIRM_TEXT = "Reimpostare i dati di AuctionatorMiniSearch?\n(Indice, lista mancanti e impostazioni UI verranno eliminati.)",
    RESET_BUTTON = "Reimposta",
    CANCEL_BUTTON = "Annulla",
    TAB_GENERAL = "Generale",
    TAB_SEARCH = "Ricerca",
    TAB_DATA = "Dati",
    SECTION_DISPLAY = "Visualizzazione",
    SECTION_SEARCH_BEHAVIOR = "Comportamento ricerca",
    SECTION_INDEX_STORAGE = "Indice e archiviazione",
    OPTION_LIVE_SEARCH_LABEL = "Ricerca live durante la digitazione",
    OPTION_LIVE_SEARCH_INFO = "Se attiva, i risultati si aggiornano mentre scrivi.",
    OPTION_MINIMAP_ICON_LABEL = "Mostra icona minimappa",
    OPTION_MINIMAP_ICON_INFO = "Mostra o nasconde il pulsante AMS sulla minimappa.",
    OPTION_MIN_CHARS_LABEL = "Caratteri minimi",
    OPTION_MIN_CHARS_INFO = "Definisce da quanti caratteri parte la ricerca.",
    OPTION_KEEP_FOCUS_LABEL = "Mantieni il focus dopo Invio",
    OPTION_KEEP_FOCUS_INFO = "Se attiva, il cursore resta nella casella di ricerca dopo Invio.",
    OPTION_DEBUG_LABEL = "Abilita modalita debug",
    OPTION_DEBUG_INFO = "Consente /ams scan e mostra l'icona debug nella finestra principale.",
    OPTION_STATUS_DETAIL_LABEL = "Messaggi di stato dettagliati",
    OPTION_STATUS_DETAIL_INFO = "Se DISATTIVATO, i messaggi lunghi di avanzamento vengono abbreviati.",
    OPTION_REFRESH_DAYS_LABEL = "Aggiorna dopo giorni",
    OPTION_REFRESH_DAYS_INFO = "Da questa eta in poi i prezzi vengono aggiornati in background.",
    OPTION_AUTODELETE_DAYS_LABEL = "Auto-elimina dopo giorni",
    OPTION_AUTODELETE_DAYS_INFO = "0 = off. Da questa eta in poi le voci vengono rimosse dall'indice AMS durante l'aggiornamento in background.",
    OPTION_REBUILD_INDEX_LABEL = "Ricostruisci indice",
    OPTION_REBUILD_INDEX_INFO = "Avvia una ricostruzione completa dal database Auctionator corrente.",
    OPTION_RESET_DATA_LABEL = "Reimposta dati",
    OPTION_RESET_DATA_INFO = "Elimina i dati AMS salvati e crea un nuovo indice.",
    CACHE_HINT = "|cffccccccNota: Alcuni oggetti appaiono nella ricerca solo dopo essere stati visti almeno una volta in gioco (cache WoW).|r",
    STATUS_NO_CHAT_EDITBOX = "Nessuna casella chat aperta disponibile per il link con Shift.",
    FALLBACK_ITEM_FMT = "Oggetto %d",
    PRICE_RANGE_PREFIX = "|cff66c0ffIntervallo|r ",
    PRICE_RANGE_TO = " |cff66c0ffa|r ",
    AGE_DAYS_FMT = "%d giorni",
    STATUS_PRICES_REFRESHING_BG = "Aggiornamento prezzi in background...",
    STATUS_PRICES_UPDATED_FMT = "Prezzi aggiornati: %d",
    STATUS_PRICES_UPDATED_REMOVED_FMT = "Prezzi aggiornati: %d | obsoleti rimossi: %d",
    STATUS_ZEROPRICE_CHECKING = "Controllo oggetti a prezzo zero...",
    STATUS_ZEROPRICE_UPDATED_FMT = "Oggetti a prezzo zero aggiornati: %d",
    STATUS_ZEROPRICE_CHECK_DONE_FMT = "Controllo prezzo zero: %d controllati",
    STATUS_INDEX_RECONCILING = "Riconciliazione indice...",
    STATUS_INDEX_RECONCILE_ADDED_FMT = "Riconciliazione indice: %d aggiunti",
    STATUS_INDEX_COMPLETE = "Indice completo",
    STATUS_INDEX_RECONCILE_PROGRESS_FMT = "Riconciliazione indice: %d%% (%d nuovi)",
    STATUS_NO_MISSING_ITEMS_OPEN = "Nessun oggetto mancante aperto",
    STATUS_ADDING_MORE_PRICES_PROGRESS_FMT = "Aggiunta di altri prezzi al database... [%d%%] Attendere!",
    STATUS_CHECKING_MISSING_PROGRESS_FMT = "Controllo oggetti mancanti... [%d%%]",
    STATUS_MISSING_UPDATED_FMT = "Mancanti aggiornati: %d nuovi, %d aperti",
    STATUS_NO_MISSING_ITEMS = "Nessun oggetto mancante",
    STATUS_CHECKING_MISSING = "Controllo oggetti mancanti...",
    STATUS_CHECKING_MISSING_COUNT_FMT = "Controllo oggetti mancanti (%d)...",
    ERROR_INVALID_PRICE_DB = "Database prezzi Auctionator non valido o vuoto!",
    STATUS_INDEX_DB_SCANNING_PROGRESS_FMT = "Scansione database indice prezzi [%d%%] Attendere!",
    LOG_INDEX_FULLY_LOADED_FMT = "[AMS] Indice caricato completamente: %d oggetti",
    STATUS_RESET_REBUILDING = "SavedVariables reimpostate. Ricostruzione indice...",
    STATUS_SCAN_COOLDOWN_FMT = "Cooldown scansione attivo: %d min rimanenti",
    ERROR_NO_PRICE_DB_SCAN = "Nessun database prezzi disponibile. Apri Auctionator ed esegui una scansione.",
    LOG_AUCTIONATOR_NOT_INSTALLED = "[AMS] Errore: L'addon 'Auctionator' non e installato o abilitato!",
    LOG_AUCTIONATOR_NOT_LOADED = "[AMS] Auctionator non caricato!",
    LOG_API_DETECTED = "[AMS] API Auctionator v1 rilevata.",
    LOG_API_NOT_FOUND_FALLBACK = "[AMS] Nota: API Auctionator v1 non trovata, uso fallback database.",
    LOG_DB_NIL_API_ACTIVE = "[AMS] AUCTIONATOR_PRICE_DATABASE e nil, modalita API attiva.",
    LOG_DB_NIL = "[AMS] AUCTIONATOR_PRICE_DATABASE e nil!",
    LOG_DB_DESERIALIZE_ERROR = "[AMS] Errore durante la deserializzazione del database prezzi!",
    LOG_NO_PRICE_DATA_REALM_FMT = "[AMS] Nessun dato prezzi per il reame: %s. Apri Auctionator ed esegui una scansione.",
    LOG_NO_PRICE_DATA_REALM_FACTION_FMT = "[AMS] Nessun dato prezzi per reame/fazione: %s",
    LOG_DB_LOADED = "[AMS] Database caricato. L'indice verra costruito all'apertura.",
    LOG_API_MODE_ACTIVE = "[AMS] Modalita API attiva. L'indice verra costruito all'apertura.",
    LOG_ERR_UI_NOT_LOADED = "[AMS] Errore: UI non caricata.",
    LOG_ERR_SEARCHBOX_NOT_INIT = "[AMS] Errore: searchBox non inizializzata! Controlla che UI.lua sia caricata correttamente e prima di Core nel .toc.",
    LOG_ERR_AUCTIONATOR_ADDON_INACTIVE = "[AMS] ERRORE: Addon Auctionator non attivo!",
    LOG_SCAN_DEBUG_ONLY = "[AMS] /ams scan e disponibile solo in modalita debug.",
    LOG_SCAN_ALREADY_RUNNING = "[AMS] Scansione gia in corso.",
    LOG_MANUAL_SCAN_STARTED = "[AMS] Scansione manuale avviata (debug).",
    LOG_DEBUG_MODE_FMT = "[AMS] Modalita debug: %s",
    STATE_ON = "ON",
    STATE_OFF = "OFF",
    LOG_DEBUG_INVALID_ITEMID_FMT = "[AMS Debug] ItemID non valido: %s",
    LOG_DEBUG_HEADER_ITEMID_FMT = "[AMS Debug] === ItemID %d ===",
    LOG_DEBUG_IN_SEARCHINDEX_FMT = "[AMS Debug] ✓ In searchIndex: %s | Prezzo: %s | Ultimo controllo: %s",
    LOG_DEBUG_NOT_IN_SEARCHINDEX = "[AMS Debug] ✗ NON in searchIndex",
    LOG_DEBUG_IN_MISSING_FMT = "[AMS Debug] ⚠ In missingItems (Retry: %d)",
    LOG_DEBUG_NOT_IN_MISSING = "[AMS Debug] ✓ NON in missingItems",
    LOG_DEBUG_API_PRICE_FMT = "[AMS Debug] ✓ Prezzo API: %s",
    LOG_DEBUG_API_PRICE_NIL = "[AMS Debug] ✗ Prezzo API: nil",
    LOG_DEBUG_IN_PRICEDB_FMT = "[AMS Debug] ✓ In priceDB chiave '%s' | Prezzo: %s",
    LOG_DEBUG_NOT_IN_PRICEDB = "[AMS Debug] ✗ NON trovato in priceDB",
    LOG_DEBUG_PRICEDB_INVALID = "[AMS Debug] ✗ priceDB e nil/non valida",
    LOG_DEBUG_NAME_BY_ID_FMT = "[AMS Debug] ✓ GetItemNameByID: %s",
    LOG_DEBUG_NAME_BY_ID_NIL = "[AMS Debug] ✗ GetItemNameByID: nil",
    LOG_DEBUG_ITEM_INFO_FMT = "[AMS Debug] ✓ GetItemInfo: %s",
    LOG_DEBUG_ITEM_INFO_NIL = "[AMS Debug] ✗ GetItemInfo: nil",
    LOG_DEBUG_END = "[AMS Debug] === Fine ===",
  },
  ptBR = {
    APP_TITLE = "Auctionator Mini Search (Retail)",
    OPTIONS_TITLE = "Auctionator Mini Search - Opcoes",
    STATUS_READY = "Pronto",
    STATUS_JOBS_ABORTED = "Tarefas canceladas",
    STATUS_INDEX_BUILDING = "Construindo indice...",
    STATUS_NO_DATA_INDEXED = "Nenhum dado indexado",
    STATUS_NO_DATA = "Sem dados",
    STATUS_NO_MATCHES = "Nenhum resultado",
    STATUS_MATCHES_FOUND_FMT = "%d resultados encontrados",
    STATUS_MATCHES_TOTAL_FMT = " (%d no total, aumente o numero de linhas para ver mais)",
    SEARCH_LABEL_FMT = "Nome do item (min. %d caracteres)",
    BUTTON_SEARCH = "Buscar",
    BUTTON_CLEAR = "Limpar",
    TOOLTIP_SEARCH = "Buscar",
    TOOLTIP_CLEAR = "Limpar",
    TOOLTIP_OPTIONS = "Opcoes",
    MINIMAP_TOOLTIP_TITLE = "Auctionator Mini Search",
    MINIMAP_TOOLTIP_HINT = "Clique esquerdo: Abrir/fechar janela\nArrastar: Mover icone",
    DEBUG_TOOLTIP_ACTIVE = "Modo debug ativo",
    DEBUG_TOOLTIP_SCAN = "/ams scan disponivel",
    DEBUG_TOOLTIP_ICON = "Icone: Chave inglesa",
    RESET_CONFIRM_TEXT = "Redefinir dados do AuctionatorMiniSearch?\n(Indice, lista de faltantes e configuracoes da UI serao removidos.)",
    RESET_BUTTON = "Redefinir",
    CANCEL_BUTTON = "Cancelar",
    TAB_GENERAL = "Geral",
    TAB_SEARCH = "Busca",
    TAB_DATA = "Dados",
    SECTION_DISPLAY = "Exibicao",
    SECTION_SEARCH_BEHAVIOR = "Comportamento de busca",
    SECTION_INDEX_STORAGE = "Indice e armazenamento",
    OPTION_LIVE_SEARCH_LABEL = "Busca em tempo real ao digitar",
    OPTION_LIVE_SEARCH_INFO = "Quando ativado, os resultados atualizam enquanto voce digita.",
    OPTION_MINIMAP_ICON_LABEL = "Mostrar icone no minimapa",
    OPTION_MINIMAP_ICON_INFO = "Mostra ou oculta o botao AMS no minimapa.",
    OPTION_MIN_CHARS_LABEL = "Caracteres minimos",
    OPTION_MIN_CHARS_INFO = "Define com quantos caracteres a busca inicia.",
    OPTION_KEEP_FOCUS_LABEL = "Manter foco apos Enter",
    OPTION_KEEP_FOCUS_INFO = "Se ativado, o cursor permanece na caixa de busca apos Enter.",
    OPTION_DEBUG_LABEL = "Ativar modo debug",
    OPTION_DEBUG_INFO = "Permite /ams scan e mostra o icone de debug na janela principal.",
    OPTION_STATUS_DETAIL_LABEL = "Mensagens de status detalhadas",
    OPTION_STATUS_DETAIL_INFO = "Quando DESLIGADO, mensagens longas de progresso sao encurtadas.",
    OPTION_REFRESH_DAYS_LABEL = "Atualizar apos dias",
    OPTION_REFRESH_DAYS_INFO = "A partir desta idade, os precos sao atualizados em segundo plano.",
    OPTION_AUTODELETE_DAYS_LABEL = "Autoexcluir apos dias",
    OPTION_AUTODELETE_DAYS_INFO = "0 = desligado. A partir desta idade, entradas sao removidas do indice AMS durante atualizacao em segundo plano.",
    OPTION_REBUILD_INDEX_LABEL = "Reconstruir indice",
    OPTION_REBUILD_INDEX_INFO = "Inicia uma reconstrucao completa a partir do banco de dados atual do Auctionator.",
    OPTION_RESET_DATA_LABEL = "Redefinir dados",
    OPTION_RESET_DATA_INFO = "Exclui dados salvos do AMS e cria um indice novo.",
    CACHE_HINT = "|cffccccccNota: Alguns itens aparecem na busca apenas apos terem sido vistos uma vez no jogo (cache do WoW).|r",
    STATUS_NO_CHAT_EDITBOX = "Nenhuma caixa de chat aberta disponivel para inserir link com Shift.",
    FALLBACK_ITEM_FMT = "Item %d",
    PRICE_RANGE_PREFIX = "|cff66c0ffFaixa|r ",
    PRICE_RANGE_TO = " |cff66c0ffate|r ",
    AGE_DAYS_FMT = "%d dias",
    STATUS_PRICES_REFRESHING_BG = "Atualizando precos em segundo plano...",
    STATUS_PRICES_UPDATED_FMT = "Precos atualizados: %d",
    STATUS_PRICES_UPDATED_REMOVED_FMT = "Precos atualizados: %d | obsoletos removidos: %d",
    STATUS_ZEROPRICE_CHECKING = "Verificando itens com preco zero...",
    STATUS_ZEROPRICE_UPDATED_FMT = "Itens com preco zero atualizados: %d",
    STATUS_ZEROPRICE_CHECK_DONE_FMT = "Verificacao preco zero: %d verificados",
    STATUS_INDEX_RECONCILING = "Reconciliando indice...",
    STATUS_INDEX_RECONCILE_ADDED_FMT = "Reconciliacao do indice: %d novos",
    STATUS_INDEX_COMPLETE = "Indice completo",
    STATUS_INDEX_RECONCILE_PROGRESS_FMT = "Reconciliacao do indice: %d%% (%d novos)",
    STATUS_NO_MISSING_ITEMS_OPEN = "Nenhum item faltante aberto",
    STATUS_ADDING_MORE_PRICES_PROGRESS_FMT = "Adicionando mais precos ao banco de dados... [%d%%] Aguarde!",
    STATUS_CHECKING_MISSING_PROGRESS_FMT = "Verificando itens faltantes... [%d%%]",
    STATUS_MISSING_UPDATED_FMT = "Faltantes atualizados: %d novos, %d abertos",
    STATUS_NO_MISSING_ITEMS = "Nenhum item faltante",
    STATUS_CHECKING_MISSING = "Verificando itens faltantes...",
    STATUS_CHECKING_MISSING_COUNT_FMT = "Verificando itens faltantes (%d)...",
    ERROR_INVALID_PRICE_DB = "Banco de precos do Auctionator invalido ou vazio!",
    STATUS_INDEX_DB_SCANNING_PROGRESS_FMT = "Escaneando banco de dados do indice de precos [%d%%] Aguarde!",
    LOG_INDEX_FULLY_LOADED_FMT = "[AMS] Indice totalmente carregado: %d itens",
    STATUS_RESET_REBUILDING = "SavedVariables redefinidas. Reconstruindo indice...",
    STATUS_SCAN_COOLDOWN_FMT = "Cooldown de scan ativo: %d min restantes",
    ERROR_NO_PRICE_DB_SCAN = "Nenhum banco de precos disponivel. Abra o Auctionator e execute um scan.",
    LOG_AUCTIONATOR_NOT_INSTALLED = "[AMS] Erro: O addon 'Auctionator' nao esta instalado ou ativado!",
    LOG_AUCTIONATOR_NOT_LOADED = "[AMS] Auctionator nao carregado!",
    LOG_API_DETECTED = "[AMS] API do Auctionator v1 detectada.",
    LOG_API_NOT_FOUND_FALLBACK = "[AMS] Aviso: API v1 do Auctionator nao encontrada, usando fallback do banco de dados.",
    LOG_DB_NIL_API_ACTIVE = "[AMS] AUCTIONATOR_PRICE_DATABASE e nil, modo API permanece ativo.",
    LOG_DB_NIL = "[AMS] AUCTIONATOR_PRICE_DATABASE e nil!",
    LOG_DB_DESERIALIZE_ERROR = "[AMS] Erro ao desserializar banco de dados de precos!",
    LOG_NO_PRICE_DATA_REALM_FMT = "[AMS] Sem dados de preco para o reino: %s. Abra o Auctionator e execute um scan.",
    LOG_NO_PRICE_DATA_REALM_FACTION_FMT = "[AMS] Sem dados de preco para reino/faccao: %s",
    LOG_DB_LOADED = "[AMS] Banco de dados carregado. O indice sera construido ao abrir.",
    LOG_API_MODE_ACTIVE = "[AMS] Modo API ativo. O indice sera construido ao abrir.",
    LOG_ERR_UI_NOT_LOADED = "[AMS] Erro: A interface nao foi carregada.",
    LOG_ERR_SEARCHBOX_NOT_INIT = "[AMS] Erro: searchBox nao inicializado! Verifique se UI.lua foi carregado corretamente e antes de Core no .toc.",
    LOG_ERR_AUCTIONATOR_ADDON_INACTIVE = "[AMS] ERRO: Addon Auctionator nao esta ativado!",
    LOG_SCAN_DEBUG_ONLY = "[AMS] /ams scan esta disponivel apenas no modo debug.",
    LOG_SCAN_ALREADY_RUNNING = "[AMS] Scan ja em execucao.",
    LOG_MANUAL_SCAN_STARTED = "[AMS] Scan manual iniciado (debug).",
    LOG_DEBUG_MODE_FMT = "[AMS] Modo debug: %s",
    STATE_ON = "ON",
    STATE_OFF = "OFF",
    LOG_DEBUG_INVALID_ITEMID_FMT = "[AMS Debug] ItemID invalido: %s",
    LOG_DEBUG_HEADER_ITEMID_FMT = "[AMS Debug] === ItemID %d ===",
    LOG_DEBUG_IN_SEARCHINDEX_FMT = "[AMS Debug] ✓ Em searchIndex: %s | Preco: %s | Ultima verificacao: %s",
    LOG_DEBUG_NOT_IN_SEARCHINDEX = "[AMS Debug] ✗ NAO esta em searchIndex",
    LOG_DEBUG_IN_MISSING_FMT = "[AMS Debug] ⚠ Em missingItems (Retry: %d)",
    LOG_DEBUG_NOT_IN_MISSING = "[AMS Debug] ✓ NAO esta em missingItems",
    LOG_DEBUG_API_PRICE_FMT = "[AMS Debug] ✓ Preco da API: %s",
    LOG_DEBUG_API_PRICE_NIL = "[AMS Debug] ✗ Preco da API: nil",
    LOG_DEBUG_IN_PRICEDB_FMT = "[AMS Debug] ✓ Em priceDB chave '%s' | Preco: %s",
    LOG_DEBUG_NOT_IN_PRICEDB = "[AMS Debug] ✗ NAO encontrado em priceDB",
    LOG_DEBUG_PRICEDB_INVALID = "[AMS Debug] ✗ priceDB e nil/invalido",
    LOG_DEBUG_NAME_BY_ID_FMT = "[AMS Debug] ✓ GetItemNameByID: %s",
    LOG_DEBUG_NAME_BY_ID_NIL = "[AMS Debug] ✗ GetItemNameByID: nil",
    LOG_DEBUG_ITEM_INFO_FMT = "[AMS Debug] ✓ GetItemInfo: %s",
    LOG_DEBUG_ITEM_INFO_NIL = "[AMS Debug] ✗ GetItemInfo: nil",
    LOG_DEBUG_END = "[AMS Debug] === Fim ===",
  },
}

AMS.locales = locales
AMS.verifiedLocales = {
  enUS = true,
  deDE = true,
}

AMS.betaLocales = {
  frFR = true,
  esES = true,
  itIT = true,
  ptBR = true,
  ruRU = true,
}

local function BuildLocaleCoverageReport()
  local reference = locales.enUS or {}
  local report = {}

  for localeKey, localeTable in pairs(locales) do
    local missing = {}
    local missingCount = 0

    for textKey, _ in pairs(reference) do
      if type(localeTable[textKey]) ~= "string" or localeTable[textKey] == "" then
        missing[textKey] = true
        missingCount = missingCount + 1
      end
    end

    report[localeKey] = {
      total = 0,
      translated = 0,
      missing = missing,
      missingCount = missingCount,
      completeness = 0,
      verified = AMS.verifiedLocales[localeKey] == true,
      beta = AMS.betaLocales[localeKey] == true,
    }
  end

  local totalKeys = 0
  for _ in pairs(reference) do
    totalKeys = totalKeys + 1
  end

  for localeKey, data in pairs(report) do
    data.total = totalKeys
    data.translated = totalKeys - data.missingCount
    if totalKeys > 0 then
      data.completeness = math.floor((data.translated / totalKeys) * 100)
    end
    report[localeKey] = data
  end

  return report
end

AMS.localeCoverage = BuildLocaleCoverageReport()

function AMS.GetLocaleCoverage(localeKey)
  if type(localeKey) == "string" and localeKey ~= "" then
    return AMS.localeCoverage[localeKey]
  end
  return AMS.localeCoverage
end

-- Returns the default locale used by AMS content selection.
function AMS.GetDefaultLocale()
  local wowLocale = GetLocale and GetLocale() or "enUS"

  if locales[wowLocale] then
    return wowLocale
  end

  local aliasMap = {
    enGB = "enUS",
    ptPT = "ptBR",
    esMX = "esES",
  }

  local mappedLocale = aliasMap[wowLocale]
  if mappedLocale and locales[mappedLocale] then
    return mappedLocale
  end

  return "enUS"
end

-- Returns the currently active AMS locale.
function AMS.GetCurrentLocale()
  return AMS.GetDefaultLocale()
end

AMS.locale = AMS.GetCurrentLocale()

-- Resolves a localized key and applies optional string formatting args.
function AMS.L(key, ...)
  AMS.locale = AMS.GetCurrentLocale()
  local lang = locales[AMS.locale] or locales.enUS
  local text = lang[key] or locales.enUS[key] or locales.deDE[key] or key
  if select("#", ...) > 0 then
    local ok, formatted = pcall(string.format, text, ...)
    if ok then
      return formatted
    end
  end
  return text
end
